/**
 * Cloudflare Workers entry (wraps the OpenNext-generated Next.js handler).
 * - Every request runs in its own scope so it gets its own database client
 *   (Workers forbid sharing sockets between requests).
 * - The cron trigger runs background jobs via /api/internal/cron.
 */
import { runInRequestScope } from "./src/lib/request-scope";
// @ts-expect-error `.open-next/worker.js` is generated by `opennextjs-cloudflare build`.
import { default as handler } from "./.open-next/worker.js";

type Env = Record<string, unknown> & { APP_URL?: string; CRON_SECRET?: string };
type Ctx = { waitUntil(p: Promise<unknown>): void; passThroughOnException?(): void };

export default {
  fetch(request: Request, env: Env, ctx: Ctx): Promise<Response> {
    return runInRequestScope(() => handler.fetch(request, env, ctx));
  },
  async scheduled(_controller: unknown, env: Env, ctx: Ctx) {
    if (!env.CRON_SECRET) {
      console.error("[cron] CRON_SECRET is not set; background jobs will not run.");
      return;
    }
    const base = env.APP_URL || "https://webscout.internal";
    const req = new Request(new URL("/api/internal/cron", base), { method: "POST", headers: { authorization: `Bearer ${env.CRON_SECRET}` } });
    ctx.waitUntil(
      runInRequestScope(async () => {
        const res: Response = await handler.fetch(req, env, ctx);
        if (!res.ok) console.error(`[cron] tick failed: HTTP ${res.status}`, await res.text());
      }),
    );
  },
};
