import { chromium } from "@playwright/test";
const [,, url, out, w = "1440", h = "900", theme = "light"] = process.argv;
const b = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || "/opt/pw-browsers/chromium" });
const ctx = await b.newContext({ viewport: { width: +w, height: +h }, colorScheme: theme });
const cookieFile = process.env.COOKIE;
if (cookieFile) await ctx.addCookies([{ name: "ws_session", value: cookieFile, url: "http://localhost:3000" }]);
const p = await ctx.newPage();
const errs = [];
p.on("console", (m) => m.type() === "error" && errs.push(m.text()));
p.on("pageerror", (e) => errs.push(e.message));
await p.goto(url, { waitUntil: "networkidle", timeout: 90000 });
await p.waitForTimeout(800);
await p.screenshot({ path: out, fullPage: process.env.FULL === "1" });
console.log("errors:", errs.slice(0, 5));
await b.close();
