// Business-type playbooks: what a genuinely better website looks like for each
// kind of local business. These drive opportunity scoring and the prompt
// generator so that a restaurant and a plumber receive fundamentally different
// specifications. Everything here is a RECOMMENDATION or INFERENCE — never a
// fact about a specific business.

import type { FeatureRef } from "./features";

export type PageSpec = { name: string; slug: string; purpose: string; sections: string[]; cta: string };
export type FormField = { label: string; type: string; required: boolean; note?: string };
export type FormSpec = { name: string; purpose: string; fields: FormField[] };
export type DesignDirection = { personality: string; typography: string; imagery: string; color: string; layout: string; motion: string };

export type Playbook = {
  id: string;
  label: string;
  family: string;
  schemaType: string;
  googleTypes: string[];
  keywords: RegExp;
  primaryGoal: string;
  primaryConversion: string;
  secondaryConversions: string[];
  audience: string[];
  visitorQuestions: string[];
  features: FeatureRef[];
  pages: PageSpec[];
  homepage: string[];
  forms: FormSpec[];
  trust: string[];
  design: DesignDirection;
  ownerInputs: string[];
  faqTopics: string[];
  seoKeywords: string[];
  compliance: string[];
  events: string[];
  /** Weight 0–1: how strongly this category benefits from a strong website (used in opportunity scoring). */
  webDependence: number;
};

const contactFields: FormField[] = [
  { label: "Full name", type: "text", required: true },
  { label: "Email", type: "email", required: true, note: "validated format" },
  { label: "Phone", type: "tel", required: false, note: "recommended for callbacks" },
];

// ───────────────────────────── Families ─────────────────────────────

function homeService(o: {
  id: string;
  label: string;
  googleTypes: string[];
  keywords: RegExp;
  services: string[];
  extraFeatures?: FeatureRef[];
  quoteFields: FormField[];
  faqTopics: string[];
  trust?: string[];
  emergency?: boolean;
  beforeAfter?: boolean;
  compliance?: string[];
  imagery: string;
  webDependence?: number;
}): Playbook {
  const servicePages = o.services.slice(0, 6).map((s) => ({
    name: s,
    slug: `/services/${s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "")}`,
    purpose: `Explain the ${s.toLowerCase()} service in depth and convert visitors who searched for it specifically.`,
    sections: ["Service hero with H1 naming the service and area served", "What's included (verified scope only)", "Process — step by step", "Relevant project photos (real only)", "Service-specific FAQs", "Quote CTA pre-selecting this service"],
    cta: `Request a ${s.toLowerCase()} quote`,
  }));
  return {
    id: o.id,
    label: o.label,
    family: "home_services",
    schemaType: "HomeAndConstructionBusiness",
    googleTypes: o.googleTypes,
    keywords: o.keywords,
    primaryGoal: "Turn local visitors into qualified quote requests and phone calls.",
    primaryConversion: "Quote request",
    secondaryConversions: ["Phone call", ...(o.emergency ? ["Emergency call"] : []), "Contact form"],
    audience: [
      "Homeowners in the service area searching for a reliable provider (likely primary segment — verify with the business)",
      "Property managers / landlords needing repeat or multi-unit work (possible segment)",
      "Small commercial clients, if the business confirms commercial work",
    ],
    visitorQuestions: [
      "Do they serve my area?",
      "Do they do the specific job I need?",
      "Are they licensed, insured and trustworthy?",
      "How quickly can they come out, and how do I get a quote?",
      "Can I see real examples of their work?",
    ],
    features: [
      { key: "quote_request", priority: "essential" },
      { key: "click_to_call", priority: "essential" },
      { key: "service_pages", priority: "essential" },
      { key: "service_areas", priority: "essential" },
      { key: "reviews", priority: "essential" },
      { key: "credentials", priority: "recommended" },
      { key: o.beforeAfter ? "before_after" : "gallery", priority: "recommended" },
      { key: "faq", priority: "recommended" },
      ...(o.emergency ? [{ key: "emergency_cta", priority: "recommended" as const }] : []),
      ...(o.extraFeatures ?? []),
    ],
    pages: [
      { name: "Home", slug: "/", purpose: "Establish trust fast and route visitors to a quote or call.", sections: [], cta: "Request a quote" },
      { name: "Services", slug: "/services", purpose: "Overview of all verified services with links to detail pages.", sections: ["Service cards with short description + link", "How it works", "Quote CTA"], cta: "Request a quote" },
      ...servicePages,
      { name: "Service Areas", slug: "/service-areas", purpose: "Confirm coverage for local searchers.", sections: ["Areas list [BUSINESS TO CONFIRM]", "Static map image", "CTA"], cta: "Check availability" },
      { name: o.beforeAfter ? "Our Work" : "Gallery", slug: "/our-work", purpose: "Show real completed projects.", sections: ["Filterable project grid", o.beforeAfter ? "Before/after sliders" : "Project details", "CTA"], cta: "Start your project" },
      { name: "Reviews", slug: "/reviews", purpose: "Social proof from real customers.", sections: ["Real testimonials [ADD REAL TESTIMONIAL]", "Links to review platforms"], cta: "Request a quote" },
      { name: "About", slug: "/about", purpose: "Humanise the business and show credentials.", sections: ["Story [BUSINESS OWNER TO PROVIDE]", "Team", "Licences & insurance [VERIFY]", "Values"], cta: "Talk to us" },
      { name: "FAQ", slug: "/faq", purpose: "Answer objections before they block a quote.", sections: ["Accordion FAQs"], cta: "Still have questions? Call us" },
      { name: "Request a Quote", slug: "/quote", purpose: "Primary conversion page.", sections: ["Multi-step quote form", "What happens next", "Phone alternative"], cta: "Submit request" },
      { name: "Contact", slug: "/contact", purpose: "All contact routes in one place.", sections: ["Phone, email, hours", "Contact form", "Service area note"], cta: "Send message" },
    ],
    homepage: [
      "Header: logo/name, primary nav (Services, Our Work, Service Areas, About, Contact), phone link, “Request a Quote” button",
      ...(o.emergency ? ["Emergency availability banner — ONLY if verified"] : []),
      "Hero: H1 combining the core service and primary city; one-line value proposition from verified facts; primary CTA “Request a quote”, secondary CTA “Call [PHONE]”; real job photo",
      "Trust strip: verified rating/review count (if provided), licensed & insured badges (only if verified), years in business ([VERIFY])",
      "Services grid: one card per verified service linking to its page",
      "Why choose us: 3–4 benefits grounded in verified facts or marked placeholders",
      o.beforeAfter ? "Before/after showcase (real photos only)" : "Recent work gallery (real photos only)",
      "How it works: request → assessment/quote → scheduled work → follow-up",
      "Testimonials (real only)",
      "Service area summary with link to full list",
      "FAQ preview (3–5 questions)",
      "Final CTA band with quote button + phone",
      "Footer: NAP (name, address/area, phone) consistent with Google Business Profile, hours, licences, links, privacy policy",
    ],
    forms: [
      {
        name: "Quote request (multi-step)",
        purpose: "Capture enough detail to estimate the job without a phone call.",
        fields: [...o.quoteFields, ...contactFields, { label: "Preferred contact method", type: "radio (phone/email/text)", required: false }, { label: "Photos", type: "file (images, max 5)", required: false }],
      },
    ],
    trust: ["Verified licences/insurance", "Real reviews with source links", "Real project photos", "Clear service area", "Named owner/team (if provided)", ...(o.trust ?? [])],
    design: {
      personality: "Dependable, clean, local, and capable — closer to a well-run trade business than a startup.",
      typography: "Sturdy geometric or grotesque sans-serif for headings (e.g. Inter Tight, Manrope, or Archivo — configurable) with a highly legible body face at 16–18px; strong weight contrast between H1 and body.",
      imagery: o.imagery,
      color: "Derive from the existing logo/brand if one exists ([BRAND COLOURS TO CONFIRM]). Otherwise a confident primary (e.g. deep blue/green family) with a high-contrast accent reserved for CTAs. All text ≥ 4.5:1 contrast.",
      layout: "Generous whitespace, 12-column grid, max content width ~1200px, card-based service grid, sticky header that compacts on scroll.",
      motion: "Subtle fade/slide-in on scroll (≤ 200ms), no parallax or autoplay carousels; disabled under prefers-reduced-motion.",
    },
    ownerInputs: [
      "Confirmed list of services (and any not offered)",
      "Service areas",
      "Licence numbers, insurance details, associations",
      "Real project photos and testimonials (with permission)",
      "Typical response time for quotes",
      "Whether pricing (or price ranges) should be published",
      ...(o.emergency ? ["Whether emergency/after-hours service is offered"] : []),
      "Logo and brand colours",
    ],
    faqTopics: o.faqTopics,
    seoKeywords: o.services.slice(0, 5).map((s) => `${s.toLowerCase()} {city}`).concat([`${o.label.toLowerCase()} near me`, `${o.label.toLowerCase()} {city}`]),
    compliance: ["Do not claim licences, insurance, warranties or guarantees unless verified.", ...(o.compliance ?? [])],
    events: ["quote_started", "quote_submitted", "phone_click", "email_click", "service_page_view", "cta_click"],
    webDependence: o.webDependence ?? 0.9,
  };
}

function foodBusiness(o: {
  id: string;
  label: string;
  googleTypes: string[];
  keywords: RegExp;
  reservations: boolean;
  extra?: FeatureRef[];
  faqTopics: string[];
  personality: string;
  imagery: string;
}): Playbook {
  return {
    id: o.id,
    label: o.label,
    family: "food",
    schemaType: o.id === "bakery" ? "Bakery" : o.id === "cafe" ? "CafeOrCoffeeShop" : "Restaurant",
    googleTypes: o.googleTypes,
    keywords: o.keywords,
    primaryGoal: o.reservations ? "Convert hungry local searchers into reservations, orders, and visits." : "Convert local searchers into visits and online orders.",
    primaryConversion: o.reservations ? "Reservation or online order" : "Online order or visit",
    secondaryConversions: ["Directions click", "Phone call", "Catering / large order enquiry", "Gift card purchase (if offered)"],
    audience: [
      "Locals deciding where to eat today, mostly on mobile (likely primary)",
      "Visitors/tourists searching nearby (possible)",
      "Office or event organisers looking for catering/large orders (if catering is offered)",
    ],
    visitorQuestions: ["What's on the menu and what does it cost?", "Are they open now?", "Where are they and is there parking?", "Can I order online or reserve?", "Do they have options for my dietary needs?"],
    features: [
      { key: "online_menu", priority: "essential" },
      { key: "hours_location", priority: "essential" },
      { key: "click_to_call", priority: "essential" },
      { key: o.reservations ? "reservations" : "online_ordering", priority: "essential" },
      { key: o.reservations ? "online_ordering" : "catering_events", priority: "recommended" },
      { key: "gallery", priority: "recommended", why: "Food and atmosphere photography is the main reason visitors choose one spot over another." },
      { key: "reviews", priority: "recommended" },
      { key: "gift_cards", priority: "optional" },
      ...(o.extra ?? []),
    ],
    pages: [
      { name: "Home", slug: "/", purpose: "Show the food and vibe, answer ‘open now?’, route to menu/order/reserve.", sections: [], cta: o.reservations ? "Reserve a table" : "Order online" },
      { name: "Menu", slug: "/menu", purpose: "Fast, readable HTML menu.", sections: ["Sticky category nav", "Menu sections with items", "Dietary legend", "Allergen statement [BUSINESS TO PROVIDE]"], cta: o.reservations ? "Reserve a table" : "Order online" },
      ...(o.reservations ? [{ name: "Reservations", slug: "/reservations", purpose: "Book a table.", sections: ["Reservation widget/link", "Group booking note", "Policies [BUSINESS TO PROVIDE]"], cta: "Reserve" }] : []),
      { name: "Order Online", slug: "/order", purpose: "Route to verified ordering options.", sections: ["Pickup/delivery options (verified only)", "Platform buttons"], cta: "Start order" },
      { name: "Catering & Events", slug: "/catering", purpose: "Capture high-value enquiries (only if offered).", sections: ["Offer summary [CONFIRM OFFERED]", "Enquiry form"], cta: "Send enquiry" },
      { name: "About", slug: "/about", purpose: "Story, people and what makes it distinct.", sections: ["Story [BUSINESS OWNER TO PROVIDE]", "Chef/team (if provided)", "Photos"], cta: "Visit us" },
      { name: "Visit / Contact", slug: "/visit", purpose: "Hours, map, parking, contact.", sections: ["Hours table [VERIFY HOURS]", "Address & directions", "Parking/transit [BUSINESS TO PROVIDE]", "Contact form"], cta: "Get directions" },
    ],
    homepage: [
      "Header: name/logo, nav (Menu, Order, Reserve*, Catering*, About, Visit), primary CTA button (*only verified options)",
      "Hero: full-bleed real food/interior photo (optimised AVIF/WebP, preloaded), H1 with cuisine + neighbourhood/city, one-line verified description, primary CTA + secondary “View menu”",
      "Open-now indicator + today's hours + address with directions link",
      "Signature dishes: 3–6 items from the verified menu with real photos and prices only if verified",
      "Ordering/reservation band with verified platforms",
      "Atmosphere gallery (real photos)",
      "Reviews (real only, with source)",
      "Catering/events teaser (only if offered)",
      "Location map (static image, link to Google Maps)",
      "Footer: NAP, hours, social links (verified), allergen notice link",
    ],
    forms: [
      {
        name: "Catering / large order enquiry",
        purpose: "Capture event orders.",
        fields: [{ label: "Event date", type: "date", required: true }, { label: "Number of guests", type: "number", required: true }, { label: "Event type", type: "select", required: false }, { label: "Service style", type: "select (verified options only)", required: false }, ...contactFields, { label: "Details / dietary needs", type: "textarea", required: false }],
      },
    ],
    trust: ["Real food photos", "Verified hours", "Real reviews", "Health/food-safety information only if provided"],
    design: {
      personality: o.personality,
      typography: "A characterful display face for headings (configurable; reflect the cuisine/brand) paired with a clean sans-serif body. Menu text ≥ 16px with clear price alignment.",
      imagery: o.imagery,
      color: "Pull from the restaurant's existing branding/interior if known ([BRAND COLOURS TO CONFIRM]); otherwise warm, appetising neutrals with one accent for CTAs. Avoid low-contrast text over photos — use overlays.",
      layout: "Image-led, edge-to-edge sections alternating with calm text blocks; menu uses a readable single column on phones and two columns on desktop.",
      motion: "Minimal: gentle image fade-ins; no autoplaying video with sound; respect reduced motion.",
    },
    ownerInputs: ["Current menu with prices and dietary info", "Verified hours incl. holidays", "Reservation and ordering platforms used", "Real food and interior photos", "Whether catering/private events are offered", "Allergen statement", "Logo/brand colours"],
    faqTopics: o.faqTopics,
    seoKeywords: [`${o.label.toLowerCase()} {city}`, `best ${o.label.toLowerCase()} near me`, `{cuisine} {city}`, `takeout {city}`],
    compliance: ["Never invent menu items, prices, dietary claims (e.g. ‘gluten-free’) or awards.", "Allergen statements must come from the business."],
    events: ["menu_view", "order_online_click", "reservation_click", "directions_click", "phone_click", "catering_submitted"],
    webDependence: 0.85,
  };
}

function appointmentBusiness(o: {
  id: string;
  label: string;
  family: string;
  schemaType: string;
  googleTypes: string[];
  keywords: RegExp;
  services: string[];
  extra?: FeatureRef[];
  faqTopics: string[];
  personality: string;
  imagery: string;
  compliance?: string[];
  ownerInputs?: string[];
  primaryConversion?: string;
  webDependence?: number;
}): Playbook {
  return {
    id: o.id,
    label: o.label,
    family: o.family,
    schemaType: o.schemaType,
    googleTypes: o.googleTypes,
    keywords: o.keywords,
    primaryGoal: "Fill the calendar with online bookings from local visitors and returning clients.",
    primaryConversion: o.primaryConversion ?? "Online booking",
    secondaryConversions: ["Phone call", "Directions", "Contact form"],
    audience: ["Local clients looking for a trusted provider (likely primary)", "Returning clients who want to rebook quickly", "New residents/visitors comparing options"],
    visitorQuestions: ["What services do they offer and what do they cost?", "Can I book online now?", "Who will I see?", "Where are they and when are they open?", "What do other clients say?"],
    features: [
      { key: "online_booking", priority: "essential" },
      { key: "click_to_call", priority: "essential" },
      { key: "pricing", priority: "recommended", why: "Service menus with prices (or ranges) are expected for this type of business and reduce booking hesitation." },
      { key: "team", priority: "recommended" },
      { key: "gallery", priority: "recommended" },
      { key: "reviews", priority: "recommended" },
      { key: "hours_location", priority: "essential" },
      { key: "faq", priority: "optional" },
      ...(o.extra ?? []),
    ],
    pages: [
      { name: "Home", slug: "/", purpose: "Show quality, build trust, route to booking.", sections: [], cta: "Book now" },
      { name: "Services & Prices", slug: "/services", purpose: "Clear service menu.", sections: ["Service categories", "Service cards: name, duration, price [VERIFY PRICE], book button"], cta: "Book this service" },
      { name: "Team", slug: "/team", purpose: "Let clients choose who they see.", sections: ["Profiles [BUSINESS TO PROVIDE]", "Book with a specific person (if supported)"], cta: "Book with …" },
      { name: "Gallery", slug: "/gallery", purpose: "Show real results.", sections: ["Grid of real work"], cta: "Book now" },
      { name: "About", slug: "/about", purpose: "Story and standards.", sections: ["Story [BUSINESS OWNER TO PROVIDE]", "Values", "Policies (cancellation, late arrival) [BUSINESS TO PROVIDE]"], cta: "Book now" },
      { name: "Contact & Location", slug: "/contact", purpose: "How to reach and find them.", sections: ["Hours [VERIFY HOURS]", "Map/directions", "Contact form"], cta: "Get directions" },
    ],
    homepage: [
      "Header: logo, nav (Services, Team, Gallery, About, Contact), “Book now” button always visible",
      "Hero: real photo of the space/work, H1 with service type + neighbourhood/city, verified one-liner, “Book now” + “View services”",
      "Highlights: 3 benefits grounded in verified facts or placeholders",
      "Popular services with prices only if verified",
      "Team preview",
      "Gallery strip (real work)",
      "Reviews (real only)",
      "Hours + location + booking CTA",
      "Footer: NAP, hours, policies, social links",
    ],
    forms: [{ name: "Contact / enquiry", purpose: "For questions not handled by booking.", fields: [...contactFields, { label: "Service of interest", type: "select", required: false }, { label: "Message", type: "textarea", required: true }] }],
    trust: ["Real reviews", "Real work photos", "Named team (if provided)", "Clear policies"],
    design: {
      personality: o.personality,
      typography: "Refined heading face (configurable) with a clean sans-serif body; generous line-height; prices in tabular figures.",
      imagery: o.imagery,
      color: "Match existing branding if known ([BRAND COLOURS TO CONFIRM]); otherwise a restrained palette with one confident accent for booking CTAs.",
      layout: "Editorial, image-forward layout; service menu as clean list/cards; sticky Book button on mobile.",
      motion: "Subtle, elegant transitions; nothing that delays booking; reduced-motion respected.",
    },
    ownerInputs: ["Service list with durations and prices (or decision not to publish)", "Booking platform", "Team names/photos/bios", "Real photos", "Policies (cancellation, deposits)", "Hours", ...(o.ownerInputs ?? [])],
    faqTopics: o.faqTopics,
    seoKeywords: o.services.slice(0, 4).map((s) => `${s.toLowerCase()} {city}`).concat([`${o.label.toLowerCase()} near me`]),
    compliance: ["Never invent prices, credentials, or results.", ...(o.compliance ?? [])],
    events: ["booking_started", "booking_completed", "phone_click", "directions_click", "service_view"],
    webDependence: o.webDependence ?? 0.85,
  };
}

function professionalService(o: {
  id: string;
  label: string;
  schemaType: string;
  googleTypes: string[];
  keywords: RegExp;
  services: string[];
  faqTopics: string[];
  compliance: string[];
  personality: string;
  extra?: FeatureRef[];
  webDependence?: number;
}): Playbook {
  return {
    id: o.id,
    label: o.label,
    family: "professional",
    schemaType: o.schemaType,
    googleTypes: o.googleTypes,
    keywords: o.keywords,
    primaryGoal: "Build credibility and turn research-stage visitors into consultation requests.",
    primaryConversion: "Consultation request",
    secondaryConversions: ["Phone call", "Email", "Resource/guide request (optional)"],
    audience: ["Individuals or businesses with a specific problem researching providers (likely primary)", "Referrals verifying the firm before calling"],
    visitorQuestions: ["Do they handle my type of matter/need?", "Are they qualified and experienced?", "What is the process and what does it cost?", "How do I get started confidentially?"],
    features: [
      { key: "case_consultation", priority: "essential" },
      { key: "service_pages", priority: "essential", why: "Each practice area/service needs its own page that speaks to that specific client need." },
      { key: "team", priority: "essential", why: "Clients hire people; credentials and bios are central to trust." },
      { key: "click_to_call", priority: "recommended" },
      { key: "reviews", priority: "recommended" },
      { key: "faq", priority: "recommended" },
      { key: "credentials", priority: "recommended" },
      { key: "blog", priority: "optional" },
      ...(o.extra ?? []),
    ],
    pages: [
      { name: "Home", slug: "/", purpose: "Position expertise and route to consultation.", sections: [], cta: "Book a consultation" },
      { name: "Services / Practice Areas", slug: "/services", purpose: "Overview of verified services.", sections: ["Service cards", "Who we help", "Process"], cta: "Discuss your situation" },
      ...o.services.slice(0, 5).map((s) => ({ name: s, slug: `/services/${s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "")}`, purpose: `Speak directly to clients needing ${s.toLowerCase()}.`, sections: ["Problem/situation framing", "How we help (verified scope)", "Process", "FAQs", "CTA"], cta: "Request a consultation" })),
      { name: "Team", slug: "/team", purpose: "Credentials and people.", sections: ["Profiles with verified credentials [BUSINESS TO PROVIDE]"], cta: "Contact" },
      { name: "About", slug: "/about", purpose: "Approach and values.", sections: ["Story [BUSINESS OWNER TO PROVIDE]", "Approach", "Memberships [VERIFY]"], cta: "Get in touch" },
      { name: "Contact", slug: "/contact", purpose: "Consultation request and details.", sections: ["Consultation form", "Office location/hours [VERIFY]", "Confidentiality note"], cta: "Submit" },
    ],
    homepage: [
      "Header: name/logo, nav (Services, Team, About, Insights*, Contact), “Book a consultation” button",
      "Hero: H1 stating who they help and with what (verified), sub-headline, consultation CTA + phone",
      "Services overview cards",
      "Why this firm: verified differentiators or placeholders",
      "Process: initial consultation → plan → engagement",
      "Team highlight",
      "Testimonials/case outcomes ONLY if verified and permitted by professional rules",
      "FAQ preview",
      "Final CTA",
      "Footer: NAP, regulatory disclosures [BUSINESS TO PROVIDE], privacy policy",
    ],
    forms: [
      {
        name: "Consultation request",
        purpose: "Primary conversion.",
        fields: [...contactFields, { label: "Service / matter type", type: "select (verified services)", required: true }, { label: "Brief description", type: "textarea (max 1000 chars)", required: true, note: "warn users not to include sensitive details" }, { label: "Preferred contact time", type: "select", required: false }],
      },
    ],
    trust: ["Verified credentials and memberships", "Named professionals", "Clear process", "Regulatory disclosures"],
    design: {
      personality: o.personality,
      typography: "Authoritative serif or refined sans for headings (configurable), highly readable body text, restrained weights.",
      imagery: "Real team and office photography; avoid cliché stock (handshakes, gavels, chess pieces).",
      color: "Use existing brand if known ([BRAND COLOURS TO CONFIRM]); otherwise deep, calm neutrals with a single accent.",
      layout: "Spacious, text-forward, strong hierarchy, scannable service pages.",
      motion: "Minimal and professional.",
    },
    ownerInputs: ["Verified list of services/practice areas", "Team bios and credentials", "Regulatory disclosures required in their jurisdiction", "Consultation process and whether it is free [VERIFY]", "Office address and hours"],
    faqTopics: o.faqTopics,
    seoKeywords: o.services.slice(0, 4).map((s) => `${s.toLowerCase()} {city}`).concat([`${o.label.toLowerCase()} {city}`]),
    compliance: o.compliance,
    events: ["consultation_started", "consultation_submitted", "phone_click", "email_click", "service_page_view"],
    webDependence: o.webDependence ?? 0.85,
  };
}

// ───────────────────────────── Playbooks ─────────────────────────────

export const PLAYBOOKS: Playbook[] = [
  foodBusiness({
    id: "restaurant",
    label: "Restaurant",
    googleTypes: ["restaurant", "meal_takeaway", "meal_delivery", "pizza_restaurant", "fast_food_restaurant", "sushi_restaurant", "indian_restaurant", "italian_restaurant", "chinese_restaurant", "mexican_restaurant", "thai_restaurant", "steak_house", "seafood_restaurant", "bar", "bar_and_grill", "hamburger_restaurant", "vegan_restaurant", "mediterranean_restaurant", "middle_eastern_restaurant", "japanese_restaurant", "korean_restaurant", "vietnamese_restaurant", "greek_restaurant", "american_restaurant", "breakfast_restaurant", "brunch_restaurant"],
    keywords: /restaurant|grill|bistro|kitchen|eatery|pizz|sushi|shawarma|taco|burger|diner|tavern|pub|bbq|steakhouse|ramen|pho|curry|kebab/i,
    reservations: true,
    extra: [{ key: "catering_events", priority: "optional" }],
    faqTopics: ["Reservations and walk-ins", "Dietary options (vegetarian, vegan, gluten-free) — verified only", "Parking and accessibility", "Large group bookings", "Takeout and delivery options"],
    personality: "Appetising, warm and confident — the site should feel like the room.",
    imagery: "Real, well-lit photography of signature dishes and the dining room. [ADD REAL PHOTO] placeholders — never stock food presented as theirs.",
  }),
  foodBusiness({
    id: "cafe",
    label: "Cafe",
    googleTypes: ["cafe", "coffee_shop", "tea_house", "juice_shop"],
    keywords: /caf[eé]|coffee|espresso|tea house|roaster|juice/i,
    reservations: false,
    faqTopics: ["Hours and busiest times", "Wi-Fi/laptop policy (if they want to state one)", "Dairy-free/vegan options — verified only", "Large orders for offices", "Seating and accessibility"],
    personality: "Inviting, relaxed, crafted — a neighbourhood favourite.",
    imagery: "Real photos of drinks, pastries, baristas and the space in natural light.",
  }),
  foodBusiness({
    id: "bakery",
    label: "Bakery",
    googleTypes: ["bakery", "dessert_shop", "donut_shop", "confectionery", "ice_cream_shop", "dessert_restaurant", "chocolate_shop"],
    keywords: /bakery|bake|patisserie|p[aâ]tisserie|cake|dessert|donut|doughnut|pastry|cupcake|gelato|ice cream/i,
    reservations: false,
    extra: [{ key: "quote_request", priority: "recommended", why: "Custom cakes and large orders need a structured order-request form with date, servings and design notes." }],
    faqTopics: ["Custom/celebration cake ordering and lead time", "Allergens and nut-free options — verified only", "Pickup/delivery options", "Daily availability"],
    personality: "Joyful, handcrafted and delicious.",
    imagery: "Close-up real product photography; custom-cake portfolio.",
  }),
  homeService({
    id: "cleaning",
    label: "Cleaning company",
    googleTypes: ["house_cleaning_service", "cleaning_service", "janitorial_service", "carpet_cleaning_service"],
    keywords: /clean|maid|janitor|custodial|carpet|pressure wash|power wash|window washing/i,
    services: ["Residential cleaning", "Commercial cleaning", "Deep cleaning", "Move-in/move-out cleaning", "Recurring cleaning plans"],
    quoteFields: [
      { label: "Service type", type: "select (verified services)", required: true },
      { label: "Property type", type: "select (house, condo/apartment, office, other)", required: true },
      { label: "Approximate size", type: "select (bedrooms/bathrooms or sq ft)", required: true },
      { label: "Preferred frequency", type: "select (one-time, weekly, bi-weekly, monthly)", required: false },
      { label: "Preferred date", type: "date", required: false },
      { label: "Address / postal code", type: "text", required: true, note: "used to confirm service area" },
      { label: "Additional details (pets, access, focus areas)", type: "textarea", required: false },
    ],
    faqTopics: ["What's included in a standard vs deep clean", "Do I need to be home?", "Supplies and equipment", "Pets", "Recurring plans and rescheduling", "Insurance/bonding — verified only"],
    beforeAfter: true,
    extraFeatures: [{ key: "online_booking", priority: "optional", why: "Recurring residential clients often prefer to book standard cleans online." }],
    imagery: "Real photos of the team at work, bright clean interiors, branded equipment/uniforms if they exist.",
  }),
  homeService({
    id: "landscaper",
    label: "Landscaping company",
    googleTypes: ["landscaper", "landscape_designer", "lawn_care_service", "gardener", "tree_service"],
    keywords: /landscap|lawn|garden|tree service|arborist|yard|hardscap|snow removal|irrigation/i,
    services: ["Landscape design", "Lawn care & maintenance", "Hardscaping", "Planting & garden beds", "Seasonal clean-up", "Snow removal"],
    quoteFields: [
      { label: "Service needed", type: "select (verified services)", required: true },
      { label: "Property type", type: "select (residential, commercial)", required: true },
      { label: "Approximate yard/area size", type: "select", required: false },
      { label: "One-time or ongoing", type: "radio", required: false },
      { label: "Address / postal code", type: "text", required: true },
      { label: "Project description", type: "textarea", required: false },
    ],
    faqTopics: ["Seasonal services and timing", "Maintenance contracts", "Design process", "Service areas", "Snow removal contracts — if offered"],
    beforeAfter: true,
    imagery: "Real completed landscapes, seasonal transformations, the crew at work.",
  }),
  homeService({
    id: "plumber",
    label: "Plumber",
    googleTypes: ["plumber"],
    keywords: /plumb|drain|sewer|water heater|pipe/i,
    services: ["Emergency plumbing", "Drain cleaning", "Water heater repair & installation", "Leak detection & repair", "Fixture installation", "Sewer line services"],
    quoteFields: [
      { label: "What do you need help with?", type: "select (verified services)", required: true },
      { label: "Is this urgent?", type: "radio (emergency / within a few days / planning)", required: true, note: "if emergency, show click-to-call prominently instead of waiting for form" },
      { label: "Property type", type: "select", required: true },
      { label: "Address / postal code", type: "text", required: true },
      { label: "Describe the problem", type: "textarea", required: false },
    ],
    faqTopics: ["Emergency availability — verified only", "Service call fees — verified only", "Areas served", "Licensing and insurance", "Warranty on work — verified only"],
    emergency: true,
    imagery: "Real technicians, vans and jobs; avoid generic stock wrenches.",
    webDependence: 0.95,
  }),
  homeService({
    id: "electrician",
    label: "Electrician",
    googleTypes: ["electrician"],
    keywords: /electric|wiring|ev charger|panel upgrade/i,
    services: ["Residential electrical", "Commercial electrical", "Panel upgrades", "EV charger installation", "Lighting installation", "Electrical repairs & troubleshooting"],
    quoteFields: [
      { label: "Type of work", type: "select (verified services)", required: true },
      { label: "Urgency", type: "radio (emergency / soon / planning)", required: true },
      { label: "Property type", type: "select", required: true },
      { label: "Address / postal code", type: "text", required: true },
      { label: "Details", type: "textarea", required: false },
    ],
    faqTopics: ["Permits and inspections", "Licensing — verified only", "Emergency service — verified only", "EV charger requirements", "Areas served"],
    emergency: true,
    compliance: ["Do not give electrical safety advice beyond what the business approves."],
    imagery: "Real electricians on the job, finished installations.",
    webDependence: 0.95,
  }),
  homeService({
    id: "contractor",
    label: "General contractor",
    googleTypes: ["general_contractor", "home_improvement_store", "carpenter", "painter", "flooring_contractor"],
    keywords: /contract|renovat|remodel|carpent|construction|build|drywall|painting|flooring|kitchen|bathroom|basement/i,
    services: ["Kitchen renovations", "Bathroom renovations", "Basement finishing", "Additions", "Flooring", "Painting"],
    quoteFields: [
      { label: "Project type", type: "select (verified services)", required: true },
      { label: "Project timeline", type: "select (ASAP, 1–3 months, 3–6 months, planning)", required: true },
      { label: "Approximate budget range", type: "select (optional)", required: false, note: "ranges only; do not imply pricing" },
      { label: "Property address / postal code", type: "text", required: true },
      { label: "Project description", type: "textarea", required: true },
    ],
    faqTopics: ["Project process and timelines", "Permits", "Warranties — verified only", "Financing — verified only", "Insurance and licensing"],
    beforeAfter: true,
    extraFeatures: [{ key: "financing", priority: "optional" }],
    imagery: "Real finished projects (professionally photographed if possible), progress shots.",
  }),
  homeService({
    id: "construction",
    label: "Construction company",
    googleTypes: ["construction_company", "roofing_contractor_commercial"],
    keywords: /construction|builders?|excavat|concrete|framing|commercial build/i,
    services: ["Commercial construction", "Residential construction", "Design-build", "Concrete & foundations", "Project management"],
    quoteFields: [
      { label: "Project type", type: "select", required: true },
      { label: "Project size/scope", type: "textarea", required: true },
      { label: "Timeline", type: "select", required: true },
      { label: "Location", type: "text", required: true },
      { label: "Company name (if commercial)", type: "text", required: false },
    ],
    faqTopics: ["Project types handled", "Safety record — verified only", "Bonding & insurance", "Process from bid to completion"],
    beforeAfter: false,
    trust: ["Safety certifications (verified only)", "Project case studies"],
    imagery: "Real project sites and completed buildings; drone shots if available.",
    webDependence: 0.75,
  }),
  homeService({
    id: "hvac",
    label: "HVAC company",
    googleTypes: ["hvac_contractor", "air_conditioning_contractor", "heating_contractor"],
    keywords: /hvac|heating|cooling|air condition|furnace|heat pump|ductwork/i,
    services: ["Furnace repair & installation", "Air conditioning", "Heat pumps", "Maintenance plans", "Duct cleaning", "Indoor air quality"],
    quoteFields: [
      { label: "Service needed", type: "select (verified services)", required: true },
      { label: "Is your system not working right now?", type: "radio", required: true },
      { label: "System type/age (if known)", type: "text", required: false },
      { label: "Address / postal code", type: "text", required: true },
      { label: "Details", type: "textarea", required: false },
    ],
    faqTopics: ["Maintenance plans — verified only", "Rebates — only programmes the business confirms", "Emergency service", "Brands serviced — verified only", "Financing — verified only"],
    emergency: true,
    extraFeatures: [{ key: "financing", priority: "optional" }, { key: "online_booking", priority: "optional", why: "Maintenance visits are routine and easy to book online." }],
    imagery: "Real technicians, equipment installs, branded vehicles.",
    webDependence: 0.95,
  }),
  homeService({
    id: "roofing",
    label: "Roofing company",
    googleTypes: ["roofing_contractor"],
    keywords: /roof|shingle|eavestrough|gutter|siding/i,
    services: ["Roof replacement", "Roof repair", "Inspections", "Gutters & eavestroughs", "Flat roofing", "Storm damage"],
    quoteFields: [
      { label: "Service needed", type: "select", required: true },
      { label: "Roof type (if known)", type: "select", required: false },
      { label: "Is there an active leak?", type: "radio", required: true },
      { label: "Address / postal code", type: "text", required: true },
      { label: "Details/photos", type: "textarea + file", required: false },
    ],
    faqTopics: ["Warranty — verified only", "Insurance claims process — only what the business confirms", "Timelines", "Materials used — verified only"],
    beforeAfter: true,
    emergency: true,
    extraFeatures: [{ key: "financing", priority: "optional" }],
    imagery: "Real roofs (drone photos ideal), crew safety gear.",
  }),
  homeService({
    id: "pest_control",
    label: "Pest control",
    googleTypes: ["pest_control_service"],
    keywords: /pest|extermin|termite|rodent|bed bug|wildlife removal/i,
    services: ["Residential pest control", "Commercial pest control", "Rodent control", "Insect treatments", "Wildlife removal", "Prevention plans"],
    quoteFields: [
      { label: "Pest problem", type: "select", required: true },
      { label: "Property type", type: "select", required: true },
      { label: "How urgent?", type: "radio", required: true },
      { label: "Address / postal code", type: "text", required: true },
      { label: "Details", type: "textarea", required: false },
    ],
    faqTopics: ["Treatment safety for kids/pets — business-approved wording only", "Preparation before treatment", "Guarantees — verified only", "Recurring plans"],
    emergency: true,
    compliance: ["Product safety claims must come from the business and product labels; do not invent."],
    imagery: "Real technicians and clean homes; avoid graphic pest imagery in hero.",
  }),
  homeService({
    id: "moving",
    label: "Moving company",
    googleTypes: ["moving_company", "storage"],
    keywords: /moving|movers|relocation|storage|packing/i,
    services: ["Local moving", "Long-distance moving", "Packing services", "Commercial moving", "Storage"],
    quoteFields: [
      { label: "Move date", type: "date", required: true },
      { label: "Moving from (postal code)", type: "text", required: true },
      { label: "Moving to (postal code)", type: "text", required: true },
      { label: "Home size", type: "select", required: true },
      { label: "Services needed (packing, storage)", type: "checkboxes (verified)", required: false },
      { label: "Special items", type: "textarea", required: false },
    ],
    faqTopics: ["How pricing is calculated — no invented rates", "Insurance/valuation coverage — verified only", "Booking lead time", "What not to pack"],
    imagery: "Real crew and trucks, careful handling.",
  }),
  appointmentBusiness({
    id: "barber",
    label: "Barber shop",
    family: "personal_care",
    schemaType: "BarberShop",
    googleTypes: ["barber_shop"],
    keywords: /barber|fade|men's grooming|shave/i,
    services: ["Haircuts", "Fades", "Beard trims", "Hot towel shaves", "Kids' cuts"],
    faqTopics: ["Walk-ins vs appointments", "Cancellation policy", "Payment methods", "Kids' cuts"],
    personality: "Sharp, confident and community-rooted.",
    imagery: "Real cuts, barbers at work, shop interior; consistent colour grading.",
  }),
  appointmentBusiness({
    id: "salon",
    label: "Hair & beauty salon",
    family: "personal_care",
    schemaType: "BeautySalon",
    googleTypes: ["beauty_salon", "hair_salon", "hair_care", "nail_salon", "spa", "day_spa", "massage", "skin_care_clinic", "beautician"],
    keywords: /salon|hair|nail|beauty|spa|lash|brow|esthetic|aesthetic|massage|wax/i,
    services: ["Haircuts & styling", "Colour", "Treatments", "Nails", "Spa services"],
    faqTopics: ["Consultations for colour", "Cancellation/deposit policy", "Products used — verified only", "Gift cards"],
    extra: [{ key: "gift_cards", priority: "optional" }],
    personality: "Polished, calm and aspirational without being cold.",
    imagery: "Real client results (with consent), the salon space, stylists.",
  }),
  appointmentBusiness({
    id: "pet_groomer",
    label: "Pet groomer",
    family: "personal_care",
    schemaType: "LocalBusiness",
    googleTypes: ["pet_care", "pet_groomer", "dog_groomer"],
    keywords: /groom|dog spa|pet spa|doggy|pet salon/i,
    services: ["Full groom", "Bath & brush", "Nail trims", "Puppy grooms", "De-shedding"],
    faqTopics: ["Vaccination requirements — verified only", "How long a groom takes", "Anxious pets", "Breed-specific pricing — verified only"],
    personality: "Friendly, caring, trustworthy with pets.",
    imagery: "Real happy pets after grooms (with owner consent), clean grooming space.",
    ownerInputs: ["Vaccination/intake requirements"],
  }),
  appointmentBusiness({
    id: "auto_detailing",
    label: "Auto detailing",
    family: "automotive",
    schemaType: "AutoWash",
    googleTypes: ["car_wash", "car_detailing"],
    keywords: /detail|car wash|ceramic coat|paint correction|tint/i,
    services: ["Interior detailing", "Exterior detailing", "Ceramic coating", "Paint correction", "Packages"],
    extra: [{ key: "before_after", priority: "essential", why: "Detailing results are visual; before/after is the strongest proof." }, { key: "pricing", priority: "essential", why: "Detailing customers compare packages by price and inclusions." }],
    faqTopics: ["Package inclusions", "How long it takes", "Mobile service — verified only", "Ceramic coating care"],
    personality: "Premium, precise, high-gloss.",
    imagery: "Real gloss shots, interiors, before/after pairs; dark sleek backgrounds work well.",
  }),
  appointmentBusiness({
    id: "mechanic",
    label: "Auto repair shop",
    family: "automotive",
    schemaType: "AutoRepair",
    googleTypes: ["car_repair", "auto_repair", "tire_shop", "oil_change", "auto_body_shop"],
    keywords: /auto repair|mechanic|garage|tire|brake|oil change|collision|auto body|transmission/i,
    services: ["General repairs", "Brakes", "Oil changes & maintenance", "Diagnostics", "Tires"],
    extra: [{ key: "credentials", priority: "recommended", why: "Certified technicians and warranties are key trust factors for auto repair." }, { key: "quote_request", priority: "recommended" }],
    faqTopics: ["Diagnostics process", "Warranty on repairs — verified only", "Makes/models serviced — verified only", "Courtesy shuttle/loaner — verified only"],
    personality: "Honest, competent, no-nonsense.",
    imagery: "Real bays, technicians, clean workshop.",
    primaryConversion: "Service appointment request",
  }),
  appointmentBusiness({
    id: "dentist",
    label: "Dental clinic",
    family: "health",
    schemaType: "Dentist",
    googleTypes: ["dentist", "dental_clinic", "orthodontist"],
    keywords: /dent|orthodont|smile|teeth|oral/i,
    services: ["General dentistry", "Cleanings & check-ups", "Cosmetic dentistry", "Emergency dental", "Orthodontics"],
    extra: [{ key: "patient_info", priority: "essential" }, { key: "emergency_cta", priority: "optional" }],
    faqTopics: ["New patients and insurance — verified plans only", "Emergency appointments", "Payment options", "What to expect at the first visit", "Accessibility"],
    personality: "Calm, clean, reassuring and modern.",
    imagery: "Real clinic, team and smiling (consenting) patients; avoid clinical close-ups in hero.",
    compliance: ["Follow dental regulatory advertising rules: no outcome guarantees, no unverified ‘best’ claims, no before/after without consent.", "Never collect health information via the generic contact form."],
    primaryConversion: "Appointment request / booking",
  }),
  appointmentBusiness({
    id: "doctor",
    label: "Medical clinic",
    family: "health",
    schemaType: "MedicalClinic",
    googleTypes: ["doctor", "medical_clinic", "physiotherapist", "chiropractor", "medical_lab", "health", "wellness_center"],
    keywords: /clinic|medical|physio|chiro|health|wellness|doctor|physician|therapy|naturopath|optometr/i,
    services: ["Appointments", "Services offered [VERIFY]", "New patients", "Virtual care (if offered)"],
    extra: [{ key: "patient_info", priority: "essential" }],
    faqTopics: ["Accepting new patients — verified only", "Insurance/direct billing — verified only", "Virtual appointments", "What to bring", "Accessibility"],
    personality: "Trustworthy, accessible, calm.",
    imagery: "Real clinic and practitioners; inclusive, respectful imagery.",
    compliance: ["No medical claims, outcomes, or advice not approved by the clinic.", "Health data must only go through compliant systems (HIPAA/PHIPA etc.).", "Accessibility (WCAG 2.2 AA) is especially important for patients."],
    primaryConversion: "Appointment booking",
  }),
  appointmentBusiness({
    id: "gym",
    label: "Gym / fitness studio",
    family: "fitness",
    schemaType: "ExerciseGym",
    googleTypes: ["gym", "fitness_center", "yoga_studio", "pilates_studio", "martial_arts_school", "sports_club"],
    keywords: /gym|fitness|crossfit|yoga|pilates|boxing|martial|training|bootcamp|spin/i,
    services: ["Memberships", "Classes", "Personal training", "Intro offers"],
    extra: [{ key: "class_schedule", priority: "essential" }, { key: "lead_magnet", priority: "optional" }],
    faqTopics: ["Membership options — verified only", "First class/trial — verified only", "What to bring", "Parking and facilities", "Cancellation policy"],
    personality: "Energetic, welcoming and motivating — not intimidating.",
    imagery: "Real members (with consent) and coaches in the actual space.",
    primaryConversion: "Trial/intro sign-up or class booking",
  }),
  {
    ...appointmentBusiness({
      id: "photographer",
      label: "Photographer",
      family: "creative",
      schemaType: "ProfessionalService",
      googleTypes: ["photographer", "photography_studio", "videographer"],
      keywords: /photo|studio|videograph|wedding film|portrait/i,
      services: ["Weddings", "Portraits", "Family sessions", "Commercial/product", "Events"],
      extra: [{ key: "portfolio_packages", priority: "essential" }],
      faqTopics: ["Booking process and deposits — verified only", "Delivery timeline", "Travel", "Usage rights"],
      personality: "Let the work lead — minimal chrome, gallery-first.",
      imagery: "Only the photographer's own portfolio; large, fast-loading imagery.",
      primaryConversion: "Enquiry / date availability request",
    }),
  },
  professionalService({
    id: "law_firm",
    label: "Law firm",
    schemaType: "LegalService",
    googleTypes: ["lawyer", "law_firm", "attorney", "legal_services", "notary_public"],
    keywords: /law|legal|attorney|lawyer|barrister|solicitor|notary|paralegal/i,
    services: ["Practice area 1 [VERIFY]", "Practice area 2 [VERIFY]", "Practice area 3 [VERIFY]"],
    faqTopics: ["Initial consultation — fee or free (verified)", "What to bring", "Fee structures — verified only", "Timelines"],
    compliance: ["Follow the jurisdiction's lawyer advertising rules; no outcome guarantees or unverifiable superlatives (‘best’, ‘expert’ where regulated).", "Include required disclaimers: website is not legal advice; contacting the firm does not create a lawyer-client relationship [LEGAL TO APPROVE].", "Do not publish case results unless permitted and verified."],
    personality: "Trustworthy, discreet, authoritative and plain-spoken.",
  }),
  professionalService({
    id: "accountant",
    label: "Accounting firm",
    schemaType: "AccountingService",
    googleTypes: ["accounting", "accountant", "tax_preparation_service", "bookkeeping_service"],
    keywords: /account|cpa|bookkeep|tax|payroll|audit/i,
    services: ["Personal tax", "Corporate tax", "Bookkeeping", "Payroll", "Advisory"],
    faqTopics: ["Deadlines", "What documents to bring", "Fees — verified only", "Remote/virtual service", "Secure document upload"],
    compliance: ["Do not give tax advice in site copy; no guarantees of refunds or savings.", "Document uploads must use a secure client portal, not email/contact forms."],
    personality: "Precise, reassuring, organised.",
  }),
  professionalService({
    id: "consultant",
    label: "Consulting business",
    schemaType: "ProfessionalService",
    googleTypes: ["consultant", "business_consultant", "management_consultant", "financial_planner", "insurance_agency"],
    keywords: /consult|advis|coach|strategy|insurance|financial plan/i,
    services: ["Core service 1 [VERIFY]", "Core service 2 [VERIFY]", "Workshops/training [VERIFY]"],
    faqTopics: ["Engagement models", "Industries served — verified only", "Timeline and deliverables"],
    compliance: ["No unverifiable ROI or performance claims.", "Financial/insurance services must include regulatory disclosures supplied by the business."],
    personality: "Sharp, clear, outcomes-focused.",
    webDependence: 0.8,
  }),
  professionalService({
    id: "marketing_agency",
    label: "Marketing agency",
    schemaType: "ProfessionalService",
    googleTypes: ["marketing_agency", "advertising_agency", "website_designer", "graphic_designer", "software_company"],
    keywords: /marketing|agency|advertis|media|digital|seo|creative|design studio|branding/i,
    services: ["Strategy", "Creative", "Digital/paid media", "Web", "Content"],
    extra: [{ key: "portfolio_packages", priority: "essential", why: "Agencies are judged on case studies and work samples." }],
    faqTopics: ["Process", "Engagement models", "Industries served"],
    compliance: ["Case study metrics must be verified and client-approved."],
    personality: "Distinctive, confident, craft-driven.",
    webDependence: 1,
  }),
  {
    ...professionalService({
      id: "real_estate",
      label: "Real estate agent",
      schemaType: "RealEstateAgent",
      googleTypes: ["real_estate_agency", "real_estate_agent", "property_management_company"],
      keywords: /real estate|realty|realtor|homes|properties|property management|brokerage/i,
      services: ["Buying", "Selling", "Home valuation", "Neighbourhood guides"],
      extra: [{ key: "listings", priority: "essential" }],
      faqTopics: ["Buying process", "Selling process", "Commission/fees — verified only", "Neighbourhoods served"],
      compliance: ["Include brokerage name and licensing disclosures required by the local regulator [VERIFY].", "No guaranteed sale prices/timelines; sold stats must be verified."],
      personality: "Polished, local-expert, trustworthy.",
    }),
    primaryConversion: "Buyer/seller consultation or home valuation request",
  },
  {
    id: "retail",
    label: "Retail store",
    family: "retail",
    schemaType: "Store",
    googleTypes: ["store", "clothing_store", "furniture_store", "jewelry_store", "shoe_store", "book_store", "gift_shop", "florist", "pet_store", "electronics_store", "hardware_store", "liquor_store", "grocery_store", "convenience_store", "bicycle_store", "sporting_goods_store", "cell_phone_store", "home_goods_store"],
    keywords: /store|shop|boutique|market|florist|jewel|furniture|apparel|clothing|goods|supply|outlet/i,
    primaryGoal: "Drive store visits and (where offered) online sales or click-and-collect.",
    primaryConversion: "Store visit (directions) or online purchase",
    secondaryConversions: ["Phone call", "Newsletter signup", "Product enquiry"],
    audience: ["Local shoppers checking hours, stock and location (likely primary)", "Gift buyers", "Online shoppers if e-commerce exists"],
    visitorQuestions: ["What do they sell?", "Are they open now?", "Is it in stock / can I buy online?", "Where are they?"],
    features: [
      { key: "hours_location", priority: "essential" },
      { key: "click_to_call", priority: "essential" },
      { key: "gallery", priority: "recommended", why: "Product/category imagery shows range and style." },
      { key: "reviews", priority: "recommended" },
      { key: "lead_magnet", priority: "optional" },
      { key: "gift_cards", priority: "optional" },
    ],
    pages: [
      { name: "Home", slug: "/", purpose: "Show range and route to visit/shop.", sections: [], cta: "Visit us" },
      { name: "Shop / Categories", slug: "/shop", purpose: "Product categories (or e-commerce if they sell online).", sections: ["Category tiles", "Featured products (verified)"], cta: "Shop now" },
      { name: "About", slug: "/about", purpose: "Story and what makes the store special.", sections: ["Story [BUSINESS OWNER TO PROVIDE]"], cta: "Visit" },
      { name: "Visit", slug: "/visit", purpose: "Hours/location.", sections: ["Hours [VERIFY]", "Directions", "Parking"], cta: "Get directions" },
      { name: "Contact", slug: "/contact", purpose: "Questions and stock enquiries.", sections: ["Form", "Phone/email"], cta: "Send" },
    ],
    homepage: ["Header with nav and Visit/Shop CTA", "Hero with real store/product photo and H1 (what + where)", "Category tiles", "Featured products (verified)", "Why shop here (verified)", "Reviews", "Hours + map", "Newsletter (optional)", "Footer NAP"],
    forms: [{ name: "Product enquiry", purpose: "Stock/product questions.", fields: [...contactFields, { label: "Product/question", type: "textarea", required: true }] }],
    trust: ["Real product photos", "Verified hours", "Return policy (if provided)"],
    design: { personality: "Reflect the store's own aesthetic and merchandise.", typography: "Brand-appropriate heading face, clean body.", imagery: "Real products and store interior.", color: "Brand-led [BRAND COLOURS TO CONFIRM].", layout: "Visual merchandising grid.", motion: "Light hover effects on product tiles." },
    ownerInputs: ["Product categories", "Whether they sell online", "Hours", "Return/exchange policy", "Photos"],
    faqTopics: ["Returns/exchanges — verified only", "Online ordering/pickup", "Gift cards", "Parking"],
    seoKeywords: ["{category} store {city}", "{category} near me"],
    compliance: ["No invented prices, stock levels, or promotions."],
    events: ["directions_click", "phone_click", "shop_click", "newsletter_signup"],
    webDependence: 0.7,
  },
  {
    id: "daycare",
    label: "Daycare / childcare",
    family: "education",
    schemaType: "ChildCare",
    googleTypes: ["child_care_agency", "preschool", "day_care_center", "daycare"],
    keywords: /daycare|day care|child ?care|preschool|montessori|nursery|early learning|kindergarten/i,
    primaryGoal: "Convert parents into tour bookings and waitlist/enrolment enquiries.",
    primaryConversion: "Tour booking / enrolment enquiry",
    secondaryConversions: ["Phone call", "Program information request"],
    audience: ["Parents of young children in the area (likely primary)", "Relocating families"],
    visitorQuestions: ["Is it licensed and safe?", "What programs and ages?", "Are there spaces available?", "What does a day look like?", "How do I book a tour?"],
    features: [
      { key: "enrollment", priority: "essential" },
      { key: "credentials", priority: "essential", why: "Licensing, staff qualifications and safety policies are the first things parents check." },
      { key: "click_to_call", priority: "essential" },
      { key: "gallery", priority: "recommended" },
      { key: "faq", priority: "recommended" },
      { key: "reviews", priority: "recommended" },
      { key: "hours_location", priority: "recommended" },
    ],
    pages: [
      { name: "Home", slug: "/", purpose: "Reassure and route to a tour.", sections: [], cta: "Book a tour" },
      { name: "Programs", slug: "/programs", purpose: "Age groups and programs (verified).", sections: ["Program cards by age [VERIFY]", "Daily schedule example [BUSINESS TO PROVIDE]"], cta: "Ask about availability" },
      { name: "Our Centre", slug: "/our-centre", purpose: "Facilities, safety, staff.", sections: ["Licensing [VERIFY]", "Safety policies [BUSINESS TO PROVIDE]", "Staff qualifications [VERIFY]", "Facility photos (no identifiable children without consent)"], cta: "Book a tour" },
      { name: "Enrolment", slug: "/enrolment", purpose: "How to enrol, fees (if published), waitlist.", sections: ["Steps", "Fees [BUSINESS TO PROVIDE]", "Tour form"], cta: "Book a tour" },
      { name: "FAQ", slug: "/faq", purpose: "Parent questions.", sections: ["Accordion"], cta: "Contact us" },
      { name: "Contact", slug: "/contact", purpose: "Details and form.", sections: ["Hours", "Map", "Form"], cta: "Send" },
    ],
    homepage: ["Header with Book a tour button", "Hero: warm real photo of the space, H1 with care type + area, tour CTA", "Trust strip: licensing (verified), ratios (verified)", "Programs by age", "A day at the centre", "Parent testimonials (real only)", "Tour CTA", "Footer"],
    forms: [{ name: "Tour / enrolment enquiry", purpose: "Primary conversion.", fields: [{ label: "Parent/guardian name", type: "text", required: true }, { label: "Email", type: "email", required: true }, { label: "Phone", type: "tel", required: true }, { label: "Child's age group", type: "select (verified programs)", required: true }, { label: "Desired start date", type: "date", required: false }, { label: "Preferred tour times", type: "text", required: false }, { label: "Questions", type: "textarea", required: false }] }],
    trust: ["Verified licensing", "Staff qualifications", "Safety policies", "Real parent testimonials"],
    design: { personality: "Warm, safe, joyful but organised.", typography: "Friendly rounded headings, very readable body.", imagery: "Real classrooms/play areas; no identifiable children without documented consent.", color: "Soft, warm palette with accessible contrast [BRAND COLOURS TO CONFIRM].", layout: "Clear, reassuring sections.", motion: "Gentle." },
    ownerInputs: ["Licence details", "Programs/ages", "Fees (if publishing)", "Hours", "Policies", "Photos with consent"],
    faqTopics: ["Licensing and ratios", "Meals/allergies — verified only", "Fees and subsidies — verified only", "Hours and holidays", "Sick policy"],
    seoKeywords: ["daycare {city}", "childcare near me", "preschool {city}"],
    compliance: ["Never publish identifiable photos of children without documented parental consent.", "No unverified claims about licensing, ratios, or curriculum accreditation."],
    events: ["tour_requested", "phone_click", "program_view"],
    webDependence: 0.9,
  },
  {
    id: "tutor",
    label: "Tutoring / education",
    family: "education",
    schemaType: "EducationalOrganization",
    googleTypes: ["tutoring_service", "school", "educational_institution", "driving_school", "music_school", "language_school", "art_school"],
    keywords: /tutor|school|academy|learning|lessons|driving school|music school|language|education|test prep/i,
    primaryGoal: "Convert parents/students into assessment or trial lesson bookings.",
    primaryConversion: "Trial lesson / assessment request",
    secondaryConversions: ["Phone call", "Program enquiry"],
    audience: ["Parents seeking help for their children (likely primary)", "Adult learners (if offered)"],
    visitorQuestions: ["Which subjects/levels?", "Who are the tutors/teachers?", "In-person or online?", "Cost and schedule?", "Results?"],
    features: [
      { key: "enrollment", priority: "essential" },
      { key: "online_booking", priority: "recommended" },
      { key: "team", priority: "recommended" },
      { key: "pricing", priority: "recommended" },
      { key: "reviews", priority: "recommended" },
      { key: "faq", priority: "recommended" },
      { key: "click_to_call", priority: "recommended" },
    ],
    pages: [
      { name: "Home", slug: "/", purpose: "Show expertise and route to trial.", sections: [], cta: "Book an assessment" },
      { name: "Programs/Subjects", slug: "/programs", purpose: "Verified subjects and levels.", sections: ["Program cards", "Formats (online/in-person)"], cta: "Enquire" },
      { name: "Tutors", slug: "/tutors", purpose: "Qualifications.", sections: ["Profiles [VERIFY]"], cta: "Book" },
      { name: "Pricing", slug: "/pricing", purpose: "Verified packages.", sections: ["[BUSINESS TO PROVIDE PRICING]"], cta: "Get started" },
      { name: "Contact", slug: "/contact", purpose: "Enquiry.", sections: ["Form", "Details"], cta: "Send" },
    ],
    homepage: ["Header with Book CTA", "Hero (who + subjects + location/online)", "Programs", "How it works", "Tutors", "Testimonials (real)", "FAQ", "CTA", "Footer"],
    forms: [{ name: "Assessment / trial request", purpose: "Primary conversion.", fields: [...contactFields, { label: "Student grade/level", type: "select", required: true }, { label: "Subject(s)", type: "checkboxes (verified)", required: true }, { label: "Format", type: "radio (online/in-person — verified)", required: false }, { label: "Goals", type: "textarea", required: false }] }],
    trust: ["Verified qualifications", "Real testimonials", "Clear policies"],
    design: { personality: "Encouraging, credible, organised.", typography: "Clean, friendly sans-serif.", imagery: "Real sessions/teachers.", color: "Brand-led [BRAND COLOURS TO CONFIRM].", layout: "Clear program cards.", motion: "Minimal." },
    ownerInputs: ["Subjects/levels", "Tutor bios", "Pricing", "Formats"],
    faqTopics: ["Scheduling", "Online vs in-person", "Progress reporting", "Cancellation policy"],
    seoKeywords: ["{subject} tutor {city}", "tutoring near me"],
    compliance: ["No guaranteed grade improvements or unverified results."],
    events: ["assessment_requested", "phone_click", "program_view"],
    webDependence: 0.9,
  },
  {
    id: "events",
    label: "Event company",
    family: "events",
    schemaType: "EventVenue",
    googleTypes: ["event_planner", "event_venue", "wedding_venue", "banquet_hall", "party_equipment_rental_service", "dj_service", "caterer"],
    keywords: /event|wedding|banquet|venue|party|dj|planner|rental|catering|decor/i,
    primaryGoal: "Convert planners into date-availability and quote enquiries.",
    primaryConversion: "Event enquiry",
    secondaryConversions: ["Phone call", "Venue tour booking"],
    audience: ["Couples and families planning celebrations", "Corporate event organisers"],
    visitorQuestions: ["Are they available on my date?", "Capacity and packages?", "What have past events looked like?", "Cost range?"],
    features: [
      { key: "quote_request", priority: "essential", why: "Event bookings start with a date + guest-count enquiry." },
      { key: "gallery", priority: "essential" },
      { key: "portfolio_packages", priority: "recommended" },
      { key: "reviews", priority: "recommended" },
      { key: "faq", priority: "recommended" },
      { key: "click_to_call", priority: "recommended" },
    ],
    pages: [
      { name: "Home", slug: "/", purpose: "Inspire and route to enquiry.", sections: [], cta: "Check your date" },
      { name: "Services/Packages", slug: "/packages", purpose: "Verified offerings.", sections: ["Packages [BUSINESS TO PROVIDE]"], cta: "Enquire" },
      { name: "Gallery", slug: "/gallery", purpose: "Real past events.", sections: ["Filter by event type"], cta: "Plan your event" },
      { name: "About", slug: "/about", purpose: "Team and story.", sections: ["[BUSINESS OWNER TO PROVIDE]"], cta: "Contact" },
      { name: "Contact", slug: "/contact", purpose: "Event enquiry.", sections: ["Enquiry form"], cta: "Send" },
    ],
    homepage: ["Header with enquiry CTA", "Hero with real event imagery", "Event types", "Gallery", "Packages preview", "Testimonials (real)", "Enquiry CTA", "Footer"],
    forms: [{ name: "Event enquiry", purpose: "Primary conversion.", fields: [{ label: "Event date", type: "date", required: true }, { label: "Event type", type: "select", required: true }, { label: "Guest count", type: "number", required: true }, { label: "Budget range (optional)", type: "select", required: false }, ...contactFields, { label: "Details", type: "textarea", required: false }] }],
    trust: ["Real event photos", "Real testimonials", "Vendor partners (if verified)"],
    design: { personality: "Elegant and celebratory.", typography: "Elegant display + clean body.", imagery: "Real events only.", color: "Brand-led.", layout: "Image-rich.", motion: "Graceful, subtle." },
    ownerInputs: ["Packages", "Capacity", "Photos", "Policies"],
    faqTopics: ["Booking deposit — verified only", "Capacity", "Vendors", "Cancellation"],
    seoKeywords: ["event venue {city}", "wedding {service} {city}"],
    compliance: ["No invented capacities, prices, or availability."],
    events: ["event_enquiry_submitted", "gallery_open", "phone_click"],
    webDependence: 0.9,
  },
  {
    id: "hotel",
    label: "Hotel / accommodation",
    family: "hospitality",
    schemaType: "Hotel",
    googleTypes: ["lodging", "hotel", "motel", "bed_and_breakfast", "inn", "resort_hotel", "campground", "guest_house", "hostel"],
    keywords: /hotel|motel|inn|suites|resort|b&b|bed and breakfast|lodge|hostel|guest house/i,
    primaryGoal: "Drive direct bookings and reduce reliance on third-party booking sites.",
    primaryConversion: "Direct booking",
    secondaryConversions: ["Phone call", "Group/event enquiry"],
    audience: ["Leisure travellers", "Business travellers", "Event/group organisers"],
    visitorQuestions: ["Availability and rates?", "Room types and amenities?", "Location and nearby attractions?", "Policies (check-in, pets, parking)?"],
    features: [
      { key: "rooms_booking", priority: "essential" },
      { key: "gallery", priority: "essential" },
      { key: "hours_location", priority: "recommended" },
      { key: "reviews", priority: "recommended" },
      { key: "faq", priority: "recommended" },
      { key: "click_to_call", priority: "recommended" },
    ],
    pages: [
      { name: "Home", slug: "/", purpose: "Inspire and route to booking.", sections: [], cta: "Check availability" },
      { name: "Rooms", slug: "/rooms", purpose: "Room types.", sections: ["Room cards with verified amenities and real photos"], cta: "Book" },
      { name: "Amenities", slug: "/amenities", purpose: "Verified amenities.", sections: [], cta: "Book" },
      { name: "Location", slug: "/location", purpose: "Area guide.", sections: ["Map", "Nearby (verified)"], cta: "Book" },
      { name: "Contact", slug: "/contact", purpose: "Enquiries.", sections: ["Form", "Phone"], cta: "Send" },
    ],
    homepage: ["Header with booking bar", "Hero with real imagery + date picker", "Room highlights", "Amenities", "Location", "Reviews", "Footer"],
    forms: [{ name: "Group / event enquiry", purpose: "Groups.", fields: [{ label: "Dates", type: "date range", required: true }, { label: "Rooms needed", type: "number", required: true }, ...contactFields, { label: "Details", type: "textarea", required: false }] }],
    trust: ["Real photos", "Verified policies", "Real reviews"],
    design: { personality: "Welcoming, evocative of the place.", typography: "Elegant headings.", imagery: "Real property photography.", color: "Brand-led.", layout: "Immersive.", motion: "Subtle." },
    ownerInputs: ["Booking engine", "Room types", "Amenities", "Policies", "Photos"],
    faqTopics: ["Check-in/out", "Parking", "Pets", "Cancellation"],
    seoKeywords: ["hotel {city}", "{type} near {landmark}"],
    compliance: ["No invented rates, ratings, or amenities."],
    events: ["availability_check", "booking_started", "phone_click"],
    webDependence: 0.95,
  },
  {
    id: "travel_agency",
    label: "Travel agency",
    family: "hospitality",
    schemaType: "TravelAgency",
    googleTypes: ["travel_agency", "tour_agency", "tourist_information_center"],
    keywords: /travel|tours?|vacation|holiday|cruise|expedition/i,
    primaryGoal: "Convert dreamers into trip-planning consultations.",
    primaryConversion: "Trip enquiry",
    secondaryConversions: ["Phone call", "Newsletter"],
    audience: ["Leisure travellers planning trips", "Groups"],
    visitorQuestions: ["Destinations/trip types?", "Why book through an agent?", "Cost?", "Credentials?"],
    features: [
      { key: "quote_request", priority: "essential", why: "Trips start with a structured enquiry (destination, dates, travellers, budget)." },
      { key: "gallery", priority: "recommended" },
      { key: "team", priority: "recommended" },
      { key: "reviews", priority: "recommended" },
      { key: "credentials", priority: "recommended", why: "Travel agency registration/bonding is a key trust signal where required." },
      { key: "lead_magnet", priority: "optional" },
    ],
    pages: [
      { name: "Home", slug: "/", purpose: "Inspire and route to enquiry.", sections: [], cta: "Plan my trip" },
      { name: "Destinations/Trips", slug: "/trips", purpose: "Verified offerings.", sections: [], cta: "Enquire" },
      { name: "About", slug: "/about", purpose: "Advisors and credentials.", sections: [], cta: "Contact" },
      { name: "Contact", slug: "/contact", purpose: "Enquiry.", sections: ["Trip enquiry form"], cta: "Send" },
    ],
    homepage: ["Header", "Hero", "Trip types", "How it works", "Advisors", "Testimonials", "CTA", "Footer"],
    forms: [{ name: "Trip enquiry", purpose: "Primary.", fields: [{ label: "Destination(s)", type: "text", required: true }, { label: "Travel dates", type: "date range", required: false }, { label: "Travellers", type: "number", required: true }, { label: "Budget range", type: "select", required: false }, ...contactFields] }],
    trust: ["Registration/bonding (verified)", "Real testimonials"],
    design: { personality: "Inspiring yet trustworthy.", typography: "Editorial.", imagery: "Real trip photos with rights.", color: "Brand-led.", layout: "Editorial.", motion: "Subtle." },
    ownerInputs: ["Specialties", "Registration details", "Advisor bios"],
    faqTopics: ["Fees", "Insurance", "Payment", "Changes/cancellations"],
    seoKeywords: ["travel agent {city}", "{trip type} packages"],
    compliance: ["Include mandatory travel-agency registration details where required [VERIFY]."],
    events: ["trip_enquiry_submitted", "phone_click"],
    webDependence: 0.85,
  },
];

export const GENERAL_PLAYBOOK: Playbook = {
  id: "general",
  label: "General local business",
  family: "general",
  schemaType: "LocalBusiness",
  googleTypes: [],
  keywords: /$^/,
  primaryGoal: "Help local visitors understand the business quickly and contact it.",
  primaryConversion: "Contact request or phone call",
  secondaryConversions: ["Directions", "Email"],
  audience: ["Local customers searching for this type of service (inferred)"],
  visitorQuestions: ["What exactly do they offer?", "Can I trust them?", "How do I contact them?", "Where/when?"],
  features: [
    { key: "click_to_call", priority: "essential" },
    { key: "contact_form", priority: "essential" },
    { key: "service_pages", priority: "recommended" },
    { key: "reviews", priority: "recommended" },
    { key: "hours_location", priority: "recommended" },
    { key: "faq", priority: "optional" },
    { key: "gallery", priority: "optional" },
  ],
  pages: [
    { name: "Home", slug: "/", purpose: "Explain and convert.", sections: [], cta: "Contact us" },
    { name: "Services", slug: "/services", purpose: "Verified offerings.", sections: ["Service cards"], cta: "Enquire" },
    { name: "About", slug: "/about", purpose: "Trust.", sections: ["Story [BUSINESS OWNER TO PROVIDE]"], cta: "Contact" },
    { name: "Contact", slug: "/contact", purpose: "Conversion.", sections: ["Form", "Phone", "Hours", "Map"], cta: "Send" },
  ],
  homepage: ["Header with contact CTA", "Hero: what + where + CTA", "Services", "Why us (verified)", "Testimonials (real)", "Contact band", "Footer NAP"],
  forms: [{ name: "Contact", purpose: "Primary conversion.", fields: [...contactFields, { label: "Message", type: "textarea", required: true }] }],
  trust: ["Real reviews", "Real photos", "Consistent NAP"],
  design: { personality: "Clear, professional and approachable.", typography: "Modern sans-serif.", imagery: "Real photos only.", color: "Brand-led [BRAND COLOURS TO CONFIRM].", layout: "Simple, well-spaced sections.", motion: "Minimal." },
  ownerInputs: ["Services", "Photos", "Hours", "Testimonials", "Brand assets"],
  faqTopics: ["Services", "Pricing approach", "Service area", "How to get started"],
  seoKeywords: ["{category} {city}", "{category} near me"],
  compliance: ["Never invent services, prices, or claims."],
  events: ["contact_submitted", "phone_click", "email_click", "directions_click"],
  webDependence: 0.75,
};

export function getPlaybook(id: string | null | undefined): Playbook {
  return PLAYBOOKS.find((p) => p.id === id) ?? GENERAL_PLAYBOOK;
}
