import type { DomainId, SkillMeta } from './types.ts';

// The skill catalog. Every skill has a matching question generator on the server
// (server/engine/generators) and is a node in the skill tree.
// grade: 0 = Kindergarten, 1..12 = school grades, 13..15 = university years.

type Def = Omit<SkillMeta, 'id' | 'title' | 'domain' | 'grade' | 'prereqs'>;
const S = (id: string, title: string, domain: DomainId, grade: number, prereqs: string[], d: Def): SkillMeta =>
  ({ id, title, domain, grade, prereqs, ...d });

export const SKILLS: SkillMeta[] = [
  // ───────────────────────── NUMBERS & OPERATIONS
  S('k-count', 'Counting', 'number', 0, [], {
    summary: 'Count objects one by one and say how many.', tags: ['counting', 'numbers'], visual: true,
    learn: ['Touch each object once as you count: 1, 2, 3…', 'The last number you say tells you how many there are.'],
    keyIdea: 'Count each thing exactly once. The last number is the total.',
    realWorld: 'Counting apples in a basket or friends at a party.',
    explainPrompt: 'How do you make sure you counted every object?', explainKeywords: ['once', 'last number', 'each', 'total'],
  }),
  S('k-compare', 'Comparing Numbers', 'number', 0, ['k-count'], {
    summary: 'Decide which number is bigger or smaller.', tags: ['compare', 'greater', 'less'],
    learn: ['A bigger number means more things.', 'On a number line, numbers get bigger as you move right.'],
    keyIdea: 'More objects → bigger number. Right on the number line → bigger.',
    realWorld: 'Which plate has more cookies?',
    explainPrompt: 'How can you tell which of two numbers is bigger?', explainKeywords: ['more', 'bigger', 'number line', 'right'],
  }),
  S('k-add10', 'Adding within 10', 'number', 0, ['k-count'], {
    summary: 'Put groups together and count them all.', tags: ['addition', 'plus'], visual: true,
    learn: ['Adding means putting groups together.', 'Start with the bigger number and count on.'],
    keyIdea: '3 + 2 means start at 3 and count on 2 more: 4, 5.',
    realWorld: '2 red balloons and 3 blue balloons make 5 balloons.',
    explainPrompt: 'What does it mean to add two numbers?', explainKeywords: ['together', 'count on', 'more', 'total'],
  }),
  S('k-sub10', 'Subtracting within 10', 'number', 0, ['k-add10'], {
    summary: 'Take some away and count what is left.', tags: ['subtraction', 'minus'], visual: true,
    learn: ['Subtracting means taking away.', 'You can count back, or think: what plus this makes that?'],
    keyIdea: '7 − 3: start at 7 and count back 3: 6, 5, 4.',
    realWorld: 'You had 7 stickers and gave away 3.',
    explainPrompt: 'How do you find what is left after taking some away?', explainKeywords: ['take away', 'left', 'count back'],
  }),
  S('place-value', 'Place Value', 'number', 1, ['k-compare'], {
    summary: 'Understand ones, tens and hundreds.', tags: ['place value', 'tens', 'hundreds', 'digits'],
    learn: ['The position of a digit tells its value. In 352, the 3 means 3 hundreds.', 'Each place is worth 10 times the place to its right.'],
    keyIdea: '352 = 300 + 50 + 2',
    realWorld: 'Reading prices like $352.',
    explainPrompt: 'Why is the 3 in 352 worth more than the 5?', explainKeywords: ['hundreds', 'tens', 'position', 'place'],
  }),
  S('add-2digit', 'Two-Digit Addition', 'number', 2, ['k-add10', 'place-value'], {
    summary: 'Add numbers up to 100 with regrouping.', tags: ['addition', 'regrouping', 'carrying'],
    learn: ['Add the ones first, then the tens.', 'If the ones add to 10 or more, regroup: carry 1 ten to the tens column.'],
    keyIdea: '47 + 38: 7 + 8 = 15 → write 5, carry 1. 4 + 3 + 1 = 8. Answer 85.',
    realWorld: 'Adding the cost of two items at a store.',
    explainPrompt: 'Explain what "carrying" means when adding.', explainKeywords: ['ones', 'tens', 'regroup', 'carry'],
  }),
  S('sub-2digit', 'Two-Digit Subtraction', 'number', 2, ['k-sub10', 'place-value'], {
    summary: 'Subtract numbers up to 100 with borrowing.', tags: ['subtraction', 'borrowing', 'regrouping'],
    learn: ['Subtract the ones first, then the tens.', 'If the top ones digit is smaller, borrow 1 ten (10 ones) from the tens.'],
    keyIdea: '52 − 27: borrow → 12 − 7 = 5, 4 − 2 = 2. Answer 25.',
    realWorld: 'Working out change after buying something.',
    explainPrompt: 'Why do we sometimes need to borrow when subtracting?', explainKeywords: ['borrow', 'tens', 'ones', 'smaller'],
  }),
  S('mult-facts', 'Multiplication Facts', 'number', 3, ['add-2digit'], {
    summary: 'Multiplication as equal groups, facts up to 12 × 12.', tags: ['multiplication', 'times tables'], visual: true,
    learn: ['Multiplication is repeated addition: 4 × 3 means 4 groups of 3.', 'Order does not matter: 4 × 3 = 3 × 4.'],
    keyIdea: 'a × b = b + b + … (a times)',
    realWorld: '4 packs of 6 juice boxes = 24 juice boxes.',
    explainPrompt: 'Explain how multiplication is related to addition.', explainKeywords: ['groups', 'repeated addition', 'equal'],
  }),
  S('div-facts', 'Division Facts', 'number', 3, ['mult-facts'], {
    summary: 'Division as sharing equally; the inverse of multiplication.', tags: ['division', 'sharing'], visual: true,
    learn: ['Division splits a total into equal groups.', 'Use multiplication facts backwards: 24 ÷ 6 = 4 because 6 × 4 = 24.'],
    keyIdea: 'a ÷ b = c  ⇔  b × c = a',
    realWorld: 'Sharing 24 sweets equally among 6 friends.',
    explainPrompt: 'How does knowing multiplication help you divide?', explainKeywords: ['inverse', 'equal groups', 'multiplication', 'share'],
  }),
  S('multi-digit-mult', 'Multi-Digit Multiplication', 'number', 4, ['mult-facts'], {
    summary: 'Multiply larger numbers using place value.', tags: ['multiplication', 'long multiplication'],
    learn: ['Break numbers into parts: 23 × 4 = 20 × 4 + 3 × 4.', 'Add the partial products.'],
    keyIdea: '(20 + 3) × 4 = 80 + 12 = 92',
    realWorld: 'Cost of 23 tickets at $4 each.',
    explainPrompt: 'Why can we split 23 into 20 + 3 when multiplying?', explainKeywords: ['distributive', 'partial products', 'place value', 'add'],
  }),
  S('long-division', 'Long Division', 'number', 5, ['div-facts', 'multi-digit-mult'], {
    summary: 'Divide multi-digit numbers, with remainders.', tags: ['division', 'remainder'],
    learn: ['Divide, multiply, subtract, bring down — repeat.', 'What is left over that cannot form a full group is the remainder.'],
    keyIdea: '157 ÷ 6 = 26 R1 because 6 × 26 = 156 and 157 − 156 = 1.',
    realWorld: 'Packing 157 eggs into cartons of 6.',
    explainPrompt: 'What does the remainder mean in a division problem?', explainKeywords: ['left over', 'remainder', 'groups', 'multiply'],
  }),
  S('order-ops', 'Order of Operations', 'number', 5, ['multi-digit-mult'], {
    summary: 'Brackets, exponents, × ÷, then + −.', tags: ['order of operations', 'bedmas', 'pemdas', 'bodmas'],
    learn: ['Work inside brackets first, then exponents.', 'Then multiply/divide left to right, then add/subtract left to right.'],
    keyIdea: 'B → E → (× ÷) → (+ −)',
    realWorld: 'Spreadsheet formulas follow the same rules.',
    explainPrompt: 'Why is 2 + 3 × 4 equal to 14 and not 20?', explainKeywords: ['multiply', 'before', 'add', 'order'],
  }),
  S('negatives', 'Integers & Negative Numbers', 'number', 6, ['sub-2digit'], {
    summary: 'Add, subtract and multiply positive and negative numbers.', tags: ['integers', 'negative'], visual: true,
    learn: ['Negative numbers are to the left of 0 on the number line.', 'Subtracting a negative is the same as adding: 5 − (−3) = 8. Two negatives multiply to a positive.'],
    keyIdea: 'a − (−b) = a + b;  (−)(−) = +;  (−)(+) = −',
    realWorld: 'Temperatures below zero; bank balances.',
    explainPrompt: 'Why does subtracting a negative number make the result bigger?', explainKeywords: ['opposite', 'add', 'number line', 'negative'],
  }),
  S('primes-factors', 'Primes, Factors & GCF', 'number', 6, ['div-facts'], {
    summary: 'Prime factorization, greatest common factor, least common multiple.', tags: ['prime', 'factor', 'gcf', 'lcm', 'number theory'],
    learn: ['A prime has exactly two factors: 1 and itself.', 'The GCF is the biggest number dividing both; the LCM is the smallest number both divide.'],
    keyIdea: '12 = 2² × 3, 18 = 2 × 3² → GCF = 2 × 3 = 6, LCM = 2² × 3² = 36',
    realWorld: 'Splitting items into identical gift bags with nothing left over.',
    explainPrompt: 'How do you find the greatest common factor of two numbers?', explainKeywords: ['factor', 'divide', 'prime', 'common', 'largest'],
  }),
  S('exponents', 'Powers & Exponents', 'number', 7, ['mult-facts'], {
    summary: 'Repeated multiplication with exponents.', tags: ['exponents', 'powers', 'squares', 'cubes'],
    learn: ['aⁿ means multiply a by itself n times.', 'Any non-zero number to the power 0 is 1.'],
    keyIdea: '2⁵ = 2 × 2 × 2 × 2 × 2 = 32',
    realWorld: 'Bacteria doubling every hour.',
    explainPrompt: 'What does 3⁴ mean, and how is it different from 3 × 4?', explainKeywords: ['repeated', 'multiply', 'itself', 'times'],
  }),
  S('square-roots', 'Square Roots', 'number', 8, ['exponents'], {
    summary: 'Find and estimate square roots.', tags: ['square root', 'radicals'],
    learn: ['√n is the non-negative number that squares to n.', 'Estimate by finding the perfect squares on either side.'],
    keyIdea: '√49 = 7 because 7² = 49.  √50 ≈ 7.07',
    realWorld: 'Finding the side length of a square room from its area.',
    explainPrompt: 'Explain what a square root is.', explainKeywords: ['square', 'multiply', 'itself', 'inverse'],
  }),
  S('sci-notation', 'Scientific Notation', 'number', 8, ['exponents'], {
    summary: 'Write very large and very small numbers compactly.', tags: ['scientific notation', 'powers of ten'],
    learn: ['Write a number as a × 10ⁿ with 1 ≤ a < 10.', 'Positive n for big numbers, negative n for small ones.'],
    keyIdea: '45 000 = 4.5 × 10⁴;  0.003 = 3 × 10⁻³',
    realWorld: 'Distances in space; sizes of cells.',
    explainPrompt: 'How do you decide the power of 10 in scientific notation?', explainKeywords: ['decimal', 'move', 'places', 'power'],
  }),

  // ───────────────────────── FRACTIONS & DECIMALS
  S('frac-intro', 'Understanding Fractions', 'fractions', 3, ['div-facts'], {
    summary: 'A fraction is part of a whole.', tags: ['fractions', 'numerator', 'denominator'], visual: true,
    learn: ['The denominator (bottom) says how many equal parts the whole is cut into.', 'The numerator (top) says how many of those parts we have.'],
    keyIdea: '3/4 = 3 of 4 equal parts',
    realWorld: 'Eating 3 slices of a pizza cut into 4 equal slices.',
    explainPrompt: 'What do the top and bottom numbers of a fraction mean?', explainKeywords: ['equal parts', 'numerator', 'denominator', 'whole'],
  }),
  S('frac-equiv', 'Equivalent Fractions', 'fractions', 4, ['frac-intro'], {
    summary: 'Different fractions that name the same amount; simplifying.', tags: ['equivalent fractions', 'simplify'], visual: true,
    learn: ['Multiplying or dividing top and bottom by the same number keeps the value.', 'Simplest form: divide top and bottom by their greatest common factor.'],
    keyIdea: '2/3 = 4/6 = 8/12;  12/18 = 2/3 (÷6)',
    realWorld: 'Half a pizza is the same as 4 slices of 8.',
    explainPrompt: 'Why are 1/2 and 4/8 equal?', explainKeywords: ['same', 'multiply', 'divide', 'top and bottom', 'numerator', 'denominator'],
  }),
  S('frac-add-like', 'Adding Fractions (Same Denominator)', 'fractions', 4, ['frac-equiv'], {
    summary: 'Add and subtract fractions with like denominators.', tags: ['adding fractions'], visual: true,
    learn: ['When the pieces are the same size, just add how many pieces.', 'Keep the denominator; add the numerators.'],
    keyIdea: '2/7 + 3/7 = 5/7',
    realWorld: 'Two friends each eat some slices of the same pizza.',
    explainPrompt: 'Why don’t we add the denominators when adding 2/7 + 3/7?', explainKeywords: ['same size', 'denominator', 'numerator', 'pieces'],
  }),
  S('frac-add-unlike', 'Adding Fractions (Different Denominators)', 'fractions', 5, ['frac-add-like', 'primes-factors'], {
    summary: 'Find a common denominator, then add.', tags: ['adding fractions', 'common denominator', 'lcd'], visual: true,
    learn: ['Pieces must be the same size before adding.', 'Rewrite both fractions over a common denominator (often the LCM), then add numerators.'],
    keyIdea: '1/3 + 1/4 = 4/12 + 3/12 = 7/12',
    realWorld: 'Mixing 1/3 cup of milk with 1/4 cup of water.',
    explainPrompt: 'Why do we need a common denominator to add 1/3 + 1/4?', explainKeywords: ['common denominator', 'same size', 'equivalent', 'lcm'],
  }),
  S('frac-mult', 'Multiplying Fractions', 'fractions', 5, ['frac-equiv'], {
    summary: 'Multiply numerators and denominators.', tags: ['multiplying fractions', 'fraction of'],
    learn: ['"Of" usually means multiply: 1/2 of 3/4 = 1/2 × 3/4.', 'Multiply tops, multiply bottoms, then simplify.'],
    keyIdea: 'a/b × c/d = ac/bd',
    realWorld: 'Using half of a 3/4-cup recipe amount.',
    explainPrompt: 'Explain why 1/2 × 1/3 is smaller than both fractions.', explainKeywords: ['part of', 'smaller', 'multiply', 'numerators', 'denominators'],
  }),
  S('frac-div', 'Dividing Fractions', 'fractions', 6, ['frac-mult'], {
    summary: 'Multiply by the reciprocal.', tags: ['dividing fractions', 'reciprocal'],
    learn: ['Dividing asks "how many of these fit into that?"', 'Keep the first fraction, flip the second, then multiply.'],
    keyIdea: 'a/b ÷ c/d = a/b × d/c',
    realWorld: 'How many 1/4-cup scoops in 3 cups?',
    explainPrompt: 'Why does dividing by 1/2 double a number?', explainKeywords: ['reciprocal', 'how many', 'fit', 'flip', 'multiply'],
  }),
  S('decimals', 'Decimal Addition & Subtraction', 'fractions', 4, ['place-value'], {
    summary: 'Line up the decimal points and add or subtract.', tags: ['decimals', 'tenths', 'hundredths'],
    learn: ['Decimal places are tenths, hundredths, thousandths…', 'Line up the decimal points so you add matching place values.'],
    keyIdea: '3.45 + 2.7 = 3.45 + 2.70 = 6.15',
    realWorld: 'Adding prices like $3.45 and $2.70.',
    explainPrompt: 'Why must decimal points line up when adding?', explainKeywords: ['place value', 'line up', 'tenths', 'hundredths'],
  }),
  S('dec-mult', 'Multiplying & Dividing Decimals', 'fractions', 5, ['decimals', 'multi-digit-mult'], {
    summary: 'Multiply as whole numbers then place the decimal.', tags: ['decimals', 'multiply decimals'],
    learn: ['Ignore the decimal points, multiply, then count the decimal places in both factors.', 'The answer has that many decimal places.'],
    keyIdea: '0.3 × 0.4 = 0.12 (1 + 1 = 2 places)',
    realWorld: 'Price of 2.5 kg of apples at $1.20/kg.',
    explainPrompt: 'Why is 0.3 × 0.4 smaller than 0.3?', explainKeywords: ['decimal places', 'less than one', 'smaller', 'count'],
  }),
  S('frac-dec-convert', 'Fractions, Decimals & Percents', 'fractions', 5, ['frac-equiv', 'decimals'], {
    summary: 'Convert between fractions, decimals and percents.', tags: ['convert', 'percent', 'decimal', 'fraction'],
    learn: ['Fraction → decimal: divide top by bottom.', 'Decimal → percent: multiply by 100.'],
    keyIdea: '3/4 = 0.75 = 75%',
    realWorld: 'A test score of 18/20 is 90%.',
    explainPrompt: 'How do you turn a fraction into a percent?', explainKeywords: ['divide', '100', 'decimal', 'percent'],
  }),

  // ───────────────────────── RATIOS & PERCENT
  S('ratios', 'Ratios', 'ratios', 6, ['frac-equiv'], {
    summary: 'Compare quantities and share in a ratio.', tags: ['ratio', 'share'],
    learn: ['A ratio a : b compares two amounts.', 'To share in a ratio, add the parts, find one part, then multiply.'],
    keyIdea: 'Share 40 in 3 : 5 → 8 parts, 1 part = 5 → 15 and 25',
    realWorld: 'Mixing paint 2 : 3 blue to yellow.',
    explainPrompt: 'How would you share an amount in the ratio 2 : 3?', explainKeywords: ['parts', 'total', 'one part', 'multiply'],
  }),
  S('unit-rate', 'Unit Rates', 'ratios', 6, ['ratios', 'long-division'], {
    summary: 'Find the amount per one unit; best buy.', tags: ['unit rate', 'per', 'unit price'],
    learn: ['A unit rate is "per 1": per hour, per item, per kg.', 'Divide the total by the number of units.'],
    keyIdea: '$12 for 4 → $3 each',
    realWorld: 'Which pack of cereal is cheaper per gram?',
    explainPrompt: 'How do you know which of two packs is the better deal?', explainKeywords: ['per', 'divide', 'one', 'compare'],
  }),
  S('percent-of', 'Percent of a Number', 'ratios', 6, ['frac-dec-convert'], {
    summary: 'Find a percentage of an amount.', tags: ['percent', 'percentage'],
    learn: ['Percent means "per hundred".', 'To find p% of N, compute p/100 × N.'],
    keyIdea: '20% of 80 = 0.20 × 80 = 16',
    realWorld: 'A 15% tip on a restaurant bill.',
    explainPrompt: 'Explain how to find 30% of a number.', explainKeywords: ['hundred', 'multiply', 'decimal', '100'],
  }),
  S('percent-change', 'Percent Increase & Decrease', 'ratios', 7, ['percent-of'], {
    summary: 'Find percent change between two values.', tags: ['percent change', 'increase', 'decrease'],
    learn: ['Percent change = (new − old) ÷ old × 100.', 'Always divide by the ORIGINAL value.'],
    keyIdea: '50 → 65: (15 ÷ 50) × 100 = 30% increase',
    realWorld: 'Price rises, population growth, sales changes.',
    explainPrompt: 'Why do we divide by the original value for percent change?', explainKeywords: ['original', 'change', 'divide', '100'],
  }),
  S('proportions', 'Proportions', 'ratios', 7, ['ratios'], {
    summary: 'Solve a/b = c/d using cross-multiplication.', tags: ['proportion', 'cross multiply', 'scale'],
    learn: ['A proportion says two ratios are equal.', 'Cross-multiply: a·d = b·c, then solve.'],
    keyIdea: '3/4 = x/20 → 4x = 60 → x = 15',
    realWorld: 'Map scales and recipe scaling.',
    explainPrompt: 'Why does cross-multiplication work?', explainKeywords: ['equal', 'ratios', 'multiply', 'both sides'],
  }),

  // ───────────────────────── ALGEBRA
  S('variables-eval', 'Variables & Expressions', 'algebra', 6, ['order-ops'], {
    summary: 'Substitute values into expressions.', tags: ['variables', 'expressions', 'substitute'],
    learn: ['A variable is a letter standing for a number.', 'To evaluate, replace the letter with its value and follow the order of operations.'],
    keyIdea: 'If x = 4, then 3x + 2 = 3(4) + 2 = 14',
    realWorld: 'A taxi costs 3 + 2m dollars for m miles.',
    explainPrompt: 'What does it mean to evaluate an expression?', explainKeywords: ['substitute', 'replace', 'value', 'order'],
  }),
  S('simplify-expr', 'Simplifying Expressions', 'algebra', 7, ['variables-eval'], {
    summary: 'Combine like terms and use the distributive property.', tags: ['like terms', 'distribute', 'simplify'],
    learn: ['Like terms have the same variable part: 3x and 5x.', 'Distribute: a(b + c) = ab + ac. Watch negative signs!'],
    keyIdea: '2(x + 3) + 4x = 2x + 6 + 4x = 6x + 6',
    realWorld: 'Simplifying a cost formula.',
    explainPrompt: 'Why can you combine 3x + 5x but not 3x + 5?', explainKeywords: ['like terms', 'same variable', 'combine'],
  }),
  S('one-step-eq', 'One-Step Equations', 'algebra', 6, ['variables-eval'], {
    summary: 'Undo one operation to find the unknown.', tags: ['equations', 'solve', 'inverse'],
    learn: ['An equation is a balance — do the same to both sides.', 'Use the inverse operation: undo + with −, undo × with ÷.'],
    keyIdea: 'x + 7 = 12 → x = 12 − 7 = 5',
    realWorld: 'You have some money plus $7 and it totals $12.',
    explainPrompt: 'Why must you do the same thing to both sides?', explainKeywords: ['balance', 'both sides', 'inverse', 'equal'],
  }),
  S('two-step-eq', 'Two-Step Equations', 'algebra', 7, ['one-step-eq'], {
    summary: 'Undo addition/subtraction, then multiplication/division.', tags: ['linear equations', 'solve'],
    learn: ['Work backwards: undo the + or − first, then the × or ÷.', 'Check by substituting your answer back in.'],
    keyIdea: '3x + 5 = 20 → 3x = 15 → x = 5',
    realWorld: 'A gym charges $5 plus $3 per class; you paid $20.',
    explainPrompt: 'In 3x + 5 = 20, why do you subtract 5 before dividing by 3?', explainKeywords: ['undo', 'inverse', 'reverse order', 'both sides'],
  }),
  S('multi-step-eq', 'Multi-Step Linear Equations', 'algebra', 8, ['two-step-eq', 'simplify-expr'], {
    summary: 'Distribute, collect variables on one side, solve.', tags: ['linear equations', 'variables both sides'],
    learn: ['Simplify each side first (distribute, combine like terms).', 'Move variable terms to one side, numbers to the other.'],
    keyIdea: '2(x + 3) = x + 10 → 2x + 6 = x + 10 → x = 4',
    realWorld: 'Comparing two phone plans to find when they cost the same.',
    explainPrompt: 'What is your strategy for solving an equation with x on both sides?', explainKeywords: ['simplify', 'distribute', 'one side', 'both sides', 'collect'],
  }),
  S('inequalities', 'Linear Inequalities', 'algebra', 7, ['two-step-eq'], {
    summary: 'Solve inequalities; flip the sign when multiplying by a negative.', tags: ['inequality', 'greater than'],
    learn: ['Solve like an equation.', 'Multiplying or dividing by a negative number reverses the inequality sign.'],
    keyIdea: '−2x < 6 → x > −3',
    realWorld: 'How many items can you buy with at most $50?',
    explainPrompt: 'Why does dividing by a negative flip the inequality?', explainKeywords: ['negative', 'reverse', 'flip', 'order'],
  }),
  S('exponent-rules', 'Exponent Laws', 'algebra', 8, ['exponents'], {
    summary: 'Product, quotient and power rules.', tags: ['exponent laws', 'powers'],
    learn: ['Same base: multiply → add exponents; divide → subtract exponents.', 'Power of a power → multiply exponents.'],
    keyIdea: 'xᵃ·xᵇ = xᵃ⁺ᵇ;  xᵃ/xᵇ = xᵃ⁻ᵇ;  (xᵃ)ᵇ = xᵃᵇ',
    realWorld: 'Compound growth and computer memory sizes.',
    explainPrompt: 'Why is x² · x³ = x⁵ and not x⁶?', explainKeywords: ['add', 'exponents', 'same base', 'factors'],
  }),
  S('systems', 'Systems of Linear Equations', 'algebra', 9, ['multi-step-eq', 'slope-intercept'], {
    summary: 'Solve two equations in two unknowns.', tags: ['systems', 'elimination', 'substitution', 'simultaneous'],
    learn: ['Substitution: solve one equation for a variable, plug into the other.', 'Elimination: add/subtract equations to cancel a variable.'],
    keyIdea: 'x + y = 10, x − y = 2 → 2x = 12 → x = 6, y = 4',
    realWorld: 'Adult and child tickets with a known total.',
    explainPrompt: 'Explain the idea behind the elimination method.', explainKeywords: ['eliminate', 'cancel', 'add', 'substitute', 'variable'],
  }),
  S('factor-quadratic', 'Factoring Quadratics', 'algebra', 10, ['multi-step-eq'], {
    summary: 'Solve x² + bx + c = 0 by factoring.', tags: ['quadratics', 'factoring', 'roots', 'zeros'],
    learn: ['Find two numbers that multiply to c and add to b.', 'If (x − p)(x − q) = 0 then x = p or x = q (zero product property).'],
    keyIdea: 'x² − 5x + 6 = (x − 2)(x − 3) = 0 → x = 2 or 3',
    realWorld: 'Finding when a thrown ball hits the ground.',
    explainPrompt: 'Why does (x − 2)(x − 3) = 0 mean x = 2 or x = 3?', explainKeywords: ['zero product', 'factor', 'zero', 'either'],
  }),
  S('quadratic-formula', 'The Quadratic Formula', 'algebra', 10, ['factor-quadratic', 'square-roots'], {
    summary: 'Solve any quadratic with the formula.', tags: ['quadratic formula', 'discriminant', 'quadratics'],
    learn: ['For ax² + bx + c = 0: x = (−b ± √(b² − 4ac)) / 2a.', 'The discriminant b² − 4ac tells how many real roots.'],
    keyIdea: 'x = (−b ± √(b² − 4ac)) / (2a)',
    realWorld: 'Projectile motion and area problems.',
    explainPrompt: 'What does the discriminant tell you?', explainKeywords: ['discriminant', 'roots', 'positive', 'negative', 'zero'],
  }),
  S('logarithms', 'Logarithms', 'algebra', 11, ['exponent-rules'], {
    summary: 'Logs undo exponents.', tags: ['logarithm', 'log', 'ln'],
    learn: ['log_b(x) = y means bʸ = x.', 'Log laws: log(ab) = log a + log b; log(aⁿ) = n log a.'],
    keyIdea: 'log₂ 32 = 5 because 2⁵ = 32',
    realWorld: 'Earthquake magnitudes and sound decibels.',
    explainPrompt: 'Explain the relationship between logarithms and exponents.', explainKeywords: ['inverse', 'exponent', 'power', 'base'],
  }),
  S('complex-numbers', 'Complex Numbers', 'algebra', 12, ['quadratic-formula'], {
    summary: 'Arithmetic with i where i² = −1.', tags: ['complex numbers', 'imaginary'],
    learn: ['A complex number is a + bi with i² = −1.', 'Multiply like binomials, then replace i² with −1.'],
    keyIdea: '(2 + 3i)(1 − i) = 2 − 2i + 3i − 3i² = 5 + i',
    realWorld: 'Electrical engineering (AC circuits) and signal processing.',
    explainPrompt: 'Why does i² equal −1, and how do you use it when multiplying?', explainKeywords: ['imaginary', 'square root', 'negative one', 'replace'],
  }),

  // ───────────────────────── FUNCTIONS & GRAPHS
  S('coord-plane', 'The Coordinate Plane', 'functions', 5, ['negatives'], {
    summary: 'Plot and read points (x, y).', tags: ['coordinates', 'graph', 'quadrant'], visual: true,
    learn: ['(x, y): x is left/right, y is up/down from the origin.', 'Quadrants are numbered I–IV counter-clockwise from the top right.'],
    keyIdea: '(3, −2) → 3 right, 2 down',
    realWorld: 'Maps, game screens, GPS grids.',
    explainPrompt: 'How do you plot the point (−3, 4)?', explainKeywords: ['left', 'up', 'x', 'y', 'origin'],
  }),
  S('slope', 'Slope', 'functions', 8, ['coord-plane'], {
    summary: 'Rise over run between two points.', tags: ['slope', 'gradient', 'rate of change'], visual: true,
    learn: ['Slope m = (y₂ − y₁)/(x₂ − x₁).', 'Positive slope goes up to the right; negative goes down.'],
    keyIdea: 'm = rise / run',
    realWorld: 'Steepness of a ramp or a road grade.',
    explainPrompt: 'What does the slope of a line tell you?', explainKeywords: ['rise', 'run', 'steep', 'rate', 'change'],
  }),
  S('slope-intercept', 'Linear Functions (y = mx + b)', 'functions', 8, ['slope', 'two-step-eq'], {
    summary: 'Read and write lines in slope-intercept form.', tags: ['linear functions', 'y=mx+b', 'intercept', 'graphing'], visual: true,
    learn: ['m is the slope; b is where the line crosses the y-axis.', 'Find b by plugging a known point into y = mx + b.'],
    keyIdea: 'y = mx + b',
    realWorld: 'Phone plan: $20 base + $5 per GB → y = 5x + 20.',
    explainPrompt: 'What do m and b represent in y = mx + b?', explainKeywords: ['slope', 'y-intercept', 'starting', 'rate'],
  }),
  S('function-eval', 'Function Notation', 'functions', 8, ['variables-eval'], {
    summary: 'Evaluate f(x) for given inputs.', tags: ['functions', 'f(x)', 'input', 'output'],
    learn: ['f(x) names a rule; f(3) means "the output when the input is 3".', 'Replace every x with the input.'],
    keyIdea: 'f(x) = x² + 1 → f(3) = 10',
    realWorld: 'A function converting Celsius to Fahrenheit.',
    explainPrompt: 'What does f(5) mean?', explainKeywords: ['input', 'output', 'substitute', 'rule'],
  }),
  S('composition', 'Composite & Inverse Functions', 'functions', 11, ['function-eval'], {
    summary: 'Evaluate f(g(x)) and find inverses.', tags: ['composition', 'inverse functions'],
    learn: ['f(g(x)): apply g first, then f.', 'An inverse undoes the function: f⁻¹(f(x)) = x.'],
    keyIdea: 'f(x) = 2x, g(x) = x + 3 → f(g(1)) = f(4) = 8',
    realWorld: 'Converting currency, then applying a fee.',
    explainPrompt: 'In f(g(x)), which function do you apply first and why?', explainKeywords: ['inside', 'first', 'output', 'input'],
  }),
  S('vertex-form', 'Quadratic Functions & Vertex Form', 'functions', 11, ['factor-quadratic'], {
    summary: 'Find the vertex and axis of symmetry of a parabola.', tags: ['parabola', 'vertex', 'quadratics', 'graphing'], visual: true,
    learn: ['y = a(x − h)² + k has vertex (h, k).', 'For y = ax² + bx + c, the vertex x-coordinate is −b/(2a).'],
    keyIdea: 'x_vertex = −b / (2a)',
    realWorld: 'The highest point of a ball’s flight.',
    explainPrompt: 'How do you find the maximum or minimum of a quadratic?', explainKeywords: ['vertex', 'symmetry', '-b/2a', 'maximum', 'minimum'],
  }),
  S('exponential-growth', 'Exponential Growth & Decay', 'functions', 11, ['exponent-rules', 'percent-change'], {
    summary: 'Model repeated percent change with a·bˣ.', tags: ['exponential', 'growth', 'decay', 'half-life'],
    learn: ['Growth by r% per period: A = P(1 + r)ᵗ.', 'Decay: A = P(1 − r)ᵗ. Half-life halves each period.'],
    keyIdea: 'A = P(1 ± r)ᵗ',
    realWorld: 'Populations, investments, radioactive decay.',
    explainPrompt: 'How is exponential growth different from linear growth?', explainKeywords: ['multiply', 'same factor', 'percent', 'add'],
  }),
  S('arith-sequence', 'Arithmetic Sequences', 'functions', 9, ['function-eval'], {
    summary: 'Sequences with a constant difference.', tags: ['sequences', 'arithmetic', 'nth term'],
    learn: ['Each term adds the common difference d.', 'nth term: aₙ = a₁ + (n − 1)d.'],
    keyIdea: 'aₙ = a₁ + (n − 1)d',
    realWorld: 'Saving the same amount each week.',
    explainPrompt: 'Why is it (n − 1)d and not nd in the formula?', explainKeywords: ['first term', 'difference', 'steps', 'n-1'],
  }),
  S('geom-series', 'Geometric Sequences & Series', 'functions', 11, ['arith-sequence', 'exponent-rules'], {
    summary: 'Constant ratio sequences and their sums.', tags: ['geometric', 'series', 'ratio'],
    learn: ['Each term multiplies by the ratio r: aₙ = a₁rⁿ⁻¹.', 'Sum of n terms: Sₙ = a₁(1 − rⁿ)/(1 − r). Infinite sum (|r| < 1): a₁/(1 − r).'],
    keyIdea: 'S∞ = a₁ / (1 − r) when |r| < 1',
    realWorld: 'Loan repayments and bouncing balls.',
    explainPrompt: 'Why can an infinite geometric series have a finite sum?', explainKeywords: ['ratio', 'less than 1', 'smaller', 'approach'],
  }),

  // ───────────────────────── GEOMETRY & MEASUREMENT
  S('k-shapes', 'Shapes', 'geometry', 0, [], {
    summary: 'Name circles, squares, triangles and more.', tags: ['shapes', 'sides', 'corners'], visual: true,
    learn: ['Shapes are named by their sides and corners.', 'A triangle has 3 sides, a square has 4 equal sides.'],
    keyIdea: 'Count the sides to name the shape.',
    realWorld: 'A slice of pizza looks like a triangle.',
    explainPrompt: 'How can you tell a square from a triangle?', explainKeywords: ['sides', 'corners', 'count', 'three', 'four'],
  }),
  S('telling-time', 'Telling Time', 'geometry', 1, ['k-count'], {
    summary: 'Read analogue clocks to the hour and minute.', tags: ['time', 'clock', 'hours', 'minutes'], visual: true,
    learn: ['The short hand shows the hour; the long hand shows minutes.', 'Each number on the clock is 5 minutes for the long hand.'],
    keyIdea: 'Long hand on 6 → 30 minutes',
    realWorld: 'Knowing when school starts.',
    explainPrompt: 'How do you read the minutes on a clock?', explainKeywords: ['long hand', 'five', 'minutes', 'count'],
  }),
  S('perimeter', 'Perimeter', 'geometry', 3, ['add-2digit'], {
    summary: 'The distance around a shape.', tags: ['perimeter', 'distance around'], visual: true,
    learn: ['Perimeter = add up all the side lengths.', 'Rectangle: P = 2(l + w).'],
    keyIdea: 'P = 2(l + w)',
    realWorld: 'Fencing needed around a garden.',
    explainPrompt: 'What is the difference between perimeter and area?', explainKeywords: ['around', 'sides', 'add', 'inside'],
  }),
  S('area-rect', 'Area of Rectangles', 'geometry', 3, ['mult-facts'], {
    summary: 'Square units that cover a rectangle.', tags: ['area', 'rectangle', 'square units'], visual: true,
    learn: ['Area counts how many unit squares cover a shape.', 'Rectangle area = length × width, measured in square units.'],
    keyIdea: 'A = l × w',
    realWorld: 'Carpet needed for a room.',
    explainPrompt: 'Why is area measured in square units?', explainKeywords: ['squares', 'cover', 'length', 'width', 'multiply'],
  }),
  S('area-triangle', 'Area of Triangles & Parallelograms', 'geometry', 6, ['area-rect'], {
    summary: 'A = ½ × base × height.', tags: ['area', 'triangle', 'parallelogram'], visual: true,
    learn: ['A triangle is half of a rectangle (or parallelogram) with the same base and height.', 'Height is perpendicular to the base.'],
    keyIdea: 'A = ½ b h',
    realWorld: 'Area of a triangular sail.',
    explainPrompt: 'Why is the area of a triangle half of base × height?', explainKeywords: ['half', 'rectangle', 'base', 'height'],
  }),
  S('angles', 'Angles & Triangles', 'geometry', 7, ['k-shapes'], {
    summary: 'Angle sums, straight lines and missing angles.', tags: ['angles', 'triangle', 'degrees'],
    learn: ['Angles in a triangle add to 180°.', 'Angles on a straight line add to 180°; around a point, 360°.'],
    keyIdea: '∠A + ∠B + ∠C = 180°',
    realWorld: 'Carpentry cuts and roof pitches.',
    explainPrompt: 'How do you find a missing angle in a triangle?', explainKeywords: ['180', 'add', 'subtract', 'sum'],
  }),
  S('circles', 'Circles: Circumference & Area', 'geometry', 7, ['area-rect', 'dec-mult'], {
    summary: 'C = 2πr and A = πr².', tags: ['circle', 'pi', 'circumference', 'radius'], visual: true, calculator: true,
    learn: ['Radius r is center-to-edge; diameter d = 2r.', 'Circumference C = 2πr; Area A = πr².'],
    keyIdea: 'C = 2πr,  A = πr²',
    realWorld: 'How much crust is on a pizza; area of a round table.',
    explainPrompt: 'What is π and why does it appear in circle formulas?', explainKeywords: ['ratio', 'circumference', 'diameter', 'constant'],
  }),
  S('volume', 'Volume of Prisms & Cylinders', 'geometry', 8, ['area-rect'], {
    summary: 'Volume = base area × height.', tags: ['volume', 'prism', 'cylinder', 'cube'], calculator: true,
    learn: ['Volume measures space inside, in cubic units.', 'For prisms and cylinders: V = (area of base) × height.'],
    keyIdea: 'V = B × h',
    realWorld: 'How much water fits in a tank.',
    explainPrompt: 'Why does volume use cubic units?', explainKeywords: ['cubes', 'three dimensions', 'base', 'height'],
  }),
  S('pythagorean', 'Pythagorean Theorem', 'geometry', 8, ['square-roots', 'area-triangle'], {
    summary: 'a² + b² = c² in right triangles.', tags: ['pythagoras', 'right triangle', 'hypotenuse'], visual: true,
    learn: ['In a right triangle, the hypotenuse c is opposite the right angle and is the longest side.', 'The squares on the legs add up to the square on the hypotenuse.'],
    keyIdea: 'a² + b² = c²',
    realWorld: 'How long a ladder must be to reach a window.',
    explainPrompt: 'Explain the Pythagorean theorem and when you can use it.', explainKeywords: ['right triangle', 'hypotenuse', 'squares', 'legs'],
  }),
  S('distance-midpoint', 'Distance & Midpoint', 'geometry', 10, ['pythagorean', 'coord-plane'], {
    summary: 'Analytic geometry on the coordinate plane.', tags: ['distance formula', 'midpoint', 'analytic geometry'], visual: true,
    learn: ['Distance d = √((x₂−x₁)² + (y₂−y₁)²) — Pythagoras on a grid.', 'Midpoint = average of the x’s and average of the y’s.'],
    keyIdea: 'd = √(Δx² + Δy²),  M = ((x₁+x₂)/2, (y₁+y₂)/2)',
    realWorld: 'Straight-line distance between two GPS points.',
    explainPrompt: 'How is the distance formula related to Pythagoras?', explainKeywords: ['right triangle', 'horizontal', 'vertical', 'hypotenuse'],
  }),
  S('vectors', 'Vectors', 'geometry', 12, ['pythagorean'], {
    summary: 'Add vectors, find magnitude and dot product.', tags: ['vectors', 'magnitude', 'dot product'],
    learn: ['A vector has size and direction, written ⟨a, b⟩.', '|⟨a, b⟩| = √(a² + b²). Dot product: ⟨a,b⟩·⟨c,d⟩ = ac + bd.'],
    keyIdea: '|v| = √(a² + b²);  u·v = |u||v|cos θ',
    realWorld: 'Forces, velocities and game physics.',
    explainPrompt: 'What does the dot product tell you about two vectors?', explainKeywords: ['angle', 'perpendicular', 'zero', 'direction'],
  }),

  // ───────────────────────── STATISTICS
  S('bar-graphs', 'Reading Bar Graphs', 'statistics', 3, ['add-2digit'], {
    summary: 'Read and compare data in bar graphs.', tags: ['graphs', 'data', 'bar chart'], visual: true,
    learn: ['Each bar’s height shows a value.', 'Compare bars by subtracting their values.'],
    keyIdea: 'Read the value where the bar ends on the scale.',
    realWorld: 'Class votes for favorite fruit.',
    explainPrompt: 'How do you find how many more votes one bar has than another?', explainKeywords: ['subtract', 'difference', 'height', 'compare'],
  }),
  S('mean-median-mode', 'Mean, Median, Mode & Range', 'statistics', 6, ['long-division'], {
    summary: 'Summarize a data set with one number.', tags: ['mean', 'median', 'mode', 'average', 'range', 'statistics'],
    learn: ['Mean: add all values, divide by how many. Median: middle value when sorted.', 'Mode: most frequent value. Range: max − min.'],
    keyIdea: 'Mean = sum ÷ count',
    realWorld: 'Average test score; typical house price (median).',
    explainPrompt: 'When is the median a better summary than the mean?', explainKeywords: ['outlier', 'middle', 'sorted', 'extreme'],
  }),
  S('std-dev', 'Standard Deviation', 'statistics', 11, ['mean-median-mode', 'square-roots'], {
    summary: 'Measure how spread out data is.', tags: ['standard deviation', 'variance', 'spread'], calculator: true,
    learn: ['Variance = average of squared distances from the mean.', 'Standard deviation = √variance (population).'],
    keyIdea: 'σ = √( Σ(x − μ)² / n )',
    realWorld: 'Consistency of a basketball player’s scoring.',
    explainPrompt: 'What does a small standard deviation tell you?', explainKeywords: ['close', 'mean', 'spread', 'consistent'],
  }),
  S('z-scores', 'Z-Scores & the Normal Distribution', 'statistics', 12, ['std-dev'], {
    summary: 'Standardize values: z = (x − μ)/σ.', tags: ['z-score', 'normal distribution', 'standardize'],
    learn: ['A z-score counts standard deviations from the mean.', 'Empirical rule: ~68% within 1σ, 95% within 2σ, 99.7% within 3σ.'],
    keyIdea: 'z = (x − μ) / σ',
    realWorld: 'Comparing scores on two different tests.',
    explainPrompt: 'What does a z-score of −2 mean?', explainKeywords: ['standard deviations', 'below', 'mean'],
  }),

  // ───────────────────────── PROBABILITY
  S('simple-prob', 'Simple Probability', 'probability', 6, ['frac-intro'], {
    summary: 'Favorable outcomes ÷ total outcomes.', tags: ['probability', 'chance', 'dice', 'coins'], visual: true,
    learn: ['Probability is between 0 (impossible) and 1 (certain).', 'P(event) = favorable outcomes ÷ total equally likely outcomes.'],
    keyIdea: 'P(rolling a 4) = 1/6',
    realWorld: 'Chance of rain, games of chance.',
    explainPrompt: 'Why is the probability of rolling an even number on a die 1/2?', explainKeywords: ['favorable', 'total', 'outcomes', 'three', 'six'],
  }),
  S('compound-prob', 'Compound Probability', 'probability', 8, ['simple-prob', 'frac-mult'], {
    summary: 'Probability of A and B, A or B.', tags: ['independent events', 'and', 'or'],
    learn: ['Independent "and": multiply probabilities.', '"Or" for mutually exclusive events: add probabilities.'],
    keyIdea: 'P(A and B) = P(A) × P(B) for independent events',
    realWorld: 'Chance two coin flips are both heads.',
    explainPrompt: 'Why do we multiply probabilities for independent events?', explainKeywords: ['independent', 'multiply', 'both', 'each'],
  }),
  S('counting', 'Permutations & Combinations', 'probability', 10, ['mult-facts'], {
    summary: 'Count arrangements and selections.', tags: ['combinations', 'permutations', 'factorial', 'choose', 'combinatorics'],
    learn: ['Permutations: order matters. nPr = n!/(n−r)!', 'Combinations: order doesn’t matter. nCr = n!/(r!(n−r)!)'],
    keyIdea: 'C(n, r) = n! / (r!(n − r)!)',
    realWorld: 'How many different pizza topping combos?',
    explainPrompt: 'When does order matter, and how does that change the count?', explainKeywords: ['order', 'arrangement', 'selection', 'divide'],
  }),
  S('binomial', 'Binomial Probability', 'probability', 12, ['counting', 'compound-prob'], {
    summary: 'P(k successes in n trials).', tags: ['binomial', 'distribution'], calculator: true,
    learn: ['n independent trials, each with success probability p.', 'P(X = k) = C(n, k) pᵏ (1 − p)ⁿ⁻ᵏ'],
    keyIdea: 'P(X = k) = C(n,k) pᵏ(1−p)ⁿ⁻ᵏ',
    realWorld: 'Chance of exactly 3 heads in 5 flips.',
    explainPrompt: 'Why is there a C(n, k) in the binomial formula?', explainKeywords: ['ways', 'arrange', 'successes', 'order'],
  }),
  S('expected-value', 'Expected Value', 'probability', 12, ['compound-prob'], {
    summary: 'Long-run average outcome.', tags: ['expected value', 'mean of distribution', 'games'],
    learn: ['E[X] = Σ (value × probability).', 'It is the average you’d get over many repetitions.'],
    keyIdea: 'E[X] = Σ x·P(x)',
    realWorld: 'Is a game or insurance policy worth it?',
    explainPrompt: 'Explain what expected value means for a game.', explainKeywords: ['average', 'long run', 'probability', 'multiply'],
  }),

  // ───────────────────────── TRIGONOMETRY
  S('trig-ratios', 'Right-Triangle Trigonometry', 'trigonometry', 10, ['pythagorean', 'proportions'], {
    summary: 'SOH-CAH-TOA to find sides and angles.', tags: ['trigonometry', 'sine', 'cosine', 'tangent', 'sohcahtoa'], visual: true, calculator: true,
    learn: ['sin = opposite/hypotenuse, cos = adjacent/hypotenuse, tan = opposite/adjacent.', 'Choose the ratio that links the side you know to the side you want.'],
    keyIdea: 'SOH CAH TOA',
    realWorld: 'Height of a tree from its shadow angle.',
    explainPrompt: 'How do you decide whether to use sin, cos or tan?', explainKeywords: ['opposite', 'adjacent', 'hypotenuse', 'known', 'unknown'],
  }),
  S('unit-circle', 'The Unit Circle', 'trigonometry', 11, ['trig-ratios'], {
    summary: 'Exact trig values and radians.', tags: ['unit circle', 'radians', 'exact values'], visual: true,
    learn: ['On the unit circle, a point at angle θ is (cos θ, sin θ).', 'π radians = 180°.'],
    keyIdea: 'cos 60° = 1/2,  sin 60° = √3/2,  π rad = 180°',
    realWorld: 'Rotations, waves and periodic motion.',
    explainPrompt: 'Why is cos θ the x-coordinate on the unit circle?', explainKeywords: ['radius 1', 'adjacent', 'hypotenuse', 'x-coordinate'],
  }),
  S('law-of-sines', 'Law of Sines & Cosines', 'trigonometry', 11, ['trig-ratios'], {
    summary: 'Solve any triangle.', tags: ['law of sines', 'law of cosines', 'oblique triangles'], calculator: true,
    learn: ['Law of sines: a/sin A = b/sin B = c/sin C.', 'Law of cosines: c² = a² + b² − 2ab cos C.'],
    keyIdea: 'c² = a² + b² − 2ab cos C',
    realWorld: 'Surveying and navigation.',
    explainPrompt: 'When would you use the law of cosines instead of the law of sines?', explainKeywords: ['two sides', 'included angle', 'three sides'],
  }),

  // ───────────────────────── CALCULUS
  S('limits', 'Limits', 'calculus', 12, ['function-eval', 'factor-quadratic'], {
    summary: 'The value a function approaches.', tags: ['limits', 'calculus', 'continuity'],
    learn: ['lim x→a f(x) is the value f(x) gets close to as x approaches a.', 'For 0/0 forms, factor and cancel, then substitute.'],
    keyIdea: 'lim x→2 (x² − 4)/(x − 2) = lim (x + 2) = 4',
    realWorld: 'Instantaneous speed is a limit of average speeds.',
    explainPrompt: 'Why can a limit exist even when f(a) is undefined?', explainKeywords: ['approach', 'close', 'near', 'not equal'],
  }),
  S('derivative-power', 'Derivatives: Power Rule', 'calculus', 12, ['limits', 'exponent-rules'], {
    summary: 'd/dx xⁿ = n xⁿ⁻¹.', tags: ['derivatives', 'differentiation', 'power rule', 'calculus'],
    learn: ['The derivative is the instantaneous rate of change (slope of the tangent).', 'Power rule: bring the exponent down, subtract one. Constants vanish.'],
    keyIdea: 'd/dx (xⁿ) = n·xⁿ⁻¹',
    realWorld: 'Velocity is the derivative of position.',
    explainPrompt: 'What does the derivative of a function represent?', explainKeywords: ['rate of change', 'slope', 'tangent', 'instantaneous'],
  }),
  S('derivative-rules', 'Product & Chain Rules', 'calculus', 12, ['derivative-power'], {
    summary: 'Differentiate products and compositions.', tags: ['chain rule', 'product rule', 'derivatives'],
    learn: ['Product: (uv)′ = u′v + uv′.', 'Chain: d/dx f(g(x)) = f′(g(x))·g′(x) — outside derivative times inside derivative.'],
    keyIdea: '(f∘g)′ = f′(g)·g′',
    realWorld: 'Related rates: how fast a balloon’s radius grows.',
    explainPrompt: 'Explain the chain rule in your own words.', explainKeywords: ['outside', 'inside', 'multiply', 'derivative'],
  }),
  S('integrals-power', 'Antiderivatives', 'calculus', 12, ['derivative-power'], {
    summary: 'Reverse the power rule; + C.', tags: ['integrals', 'antiderivative', 'integration'],
    learn: ['∫ xⁿ dx = xⁿ⁺¹/(n+1) + C (n ≠ −1).', 'The + C appears because constants differentiate to zero.'],
    keyIdea: '∫ xⁿ dx = xⁿ⁺¹/(n + 1) + C',
    realWorld: 'Recovering distance from a velocity formula.',
    explainPrompt: 'Why do antiderivatives include + C?', explainKeywords: ['constant', 'derivative', 'zero', 'family'],
  }),
  S('definite-integrals', 'Definite Integrals', 'calculus', 12, ['integrals-power'], {
    summary: 'Area under a curve with the Fundamental Theorem.', tags: ['definite integral', 'area under curve', 'ftc'],
    learn: ['∫ₐᵇ f(x) dx = F(b) − F(a) where F′ = f.', 'It measures signed area between the curve and the x-axis.'],
    keyIdea: '∫ₐᵇ f = F(b) − F(a)',
    realWorld: 'Total distance from a speed graph.',
    explainPrompt: 'What does the Fundamental Theorem of Calculus connect?', explainKeywords: ['derivative', 'integral', 'antiderivative', 'area'],
  }),
  S('optimization', 'Optimization', 'calculus', 13, ['derivative-rules'], {
    summary: 'Find maxima/minima with derivatives.', tags: ['optimization', 'max', 'min', 'critical points'],
    learn: ['Set f′(x) = 0 to find critical points.', 'Check with the second derivative or endpoints.'],
    keyIdea: 'f′(x) = 0 at local extrema',
    realWorld: 'Maximizing area with limited fencing; minimizing cost.',
    explainPrompt: 'Why is the derivative zero at a maximum?', explainKeywords: ['slope', 'flat', 'tangent', 'horizontal'],
  }),
  S('integration-by-parts', 'Integration by Parts', 'calculus', 13, ['integrals-power', 'derivative-rules'], {
    summary: '∫u dv = uv − ∫v du.', tags: ['integration by parts', 'calculus ii'],
    learn: ['Comes from the product rule.', 'Choose u to get simpler when differentiated (LIATE).'],
    keyIdea: '∫ u dv = uv − ∫ v du',
    realWorld: 'Signal processing and probability expectations.',
    explainPrompt: 'How do you choose u in integration by parts?', explainKeywords: ['simpler', 'differentiate', 'liate', 'product rule'],
  }),
  S('partial-derivatives', 'Partial Derivatives', 'calculus', 14, ['derivative-rules'], {
    summary: 'Differentiate with respect to one variable at a time.', tags: ['multivariable calculus', 'partial derivative', 'gradient'],
    learn: ['∂f/∂x treats every other variable as a constant.', 'The gradient ∇f collects all partial derivatives.'],
    keyIdea: 'f = x²y → ∂f/∂x = 2xy, ∂f/∂y = x²',
    realWorld: 'Sensitivity of profit to price vs. quantity.',
    explainPrompt: 'What does ∂f/∂x measure?', explainKeywords: ['rate of change', 'constant', 'other variables', 'x direction'],
  }),
  S('separable-ode', 'Separable Differential Equations', 'calculus', 14, ['integrals-power', 'logarithms'], {
    summary: 'Solve dy/dx = ky and similar equations.', tags: ['differential equations', 'ode', 'exponential model'], calculator: true,
    learn: ['Separate: put all y’s on one side, x’s on the other, then integrate.', 'dy/dt = ky → y = y₀eᵏᵗ.'],
    keyIdea: 'dy/dt = ky ⇒ y = y₀ e^{kt}',
    realWorld: 'Population growth, cooling, radioactive decay.',
    explainPrompt: 'Why does dy/dt = ky lead to exponential solutions?', explainKeywords: ['proportional', 'rate', 'integrate', 'exponential'],
  }),
  S('taylor-series', 'Taylor Series', 'calculus', 14, ['derivative-rules', 'geom-series'], {
    summary: 'Approximate functions by polynomials.', tags: ['taylor', 'maclaurin', 'series'],
    learn: ['f(x) ≈ Σ f⁽ⁿ⁾(a)/n! (x − a)ⁿ.', 'eˣ = 1 + x + x²/2! + x³/3! + …'],
    keyIdea: 'cₙ = f⁽ⁿ⁾(a) / n!',
    realWorld: 'How calculators compute sin and eˣ.',
    explainPrompt: 'Why do Taylor polynomials match a function near a point?', explainKeywords: ['derivatives', 'match', 'polynomial', 'approximate'],
  }),
  S('series-convergence', 'Series Convergence', 'calculus', 14, ['geom-series', 'limits'], {
    summary: 'Decide whether infinite series converge.', tags: ['convergence', 'series tests', 'real analysis'],
    learn: ['Geometric Σrⁿ converges iff |r| < 1. p-series Σ1/nᵖ converges iff p > 1.', 'If terms don’t go to 0, the series diverges (divergence test).'],
    keyIdea: 'Σ 1/nᵖ converges ⇔ p > 1',
    realWorld: 'Whether repeated payments or errors add up to a finite total.',
    explainPrompt: 'Why does Σ1/n diverge even though its terms go to 0?', explainKeywords: ['harmonic', 'grow', 'slowly', 'compare'],
  }),
  S('newtons-method', "Newton's Method", 'calculus', 14, ['derivative-power'], {
    summary: 'Numerical root finding.', tags: ['numerical methods', 'newton', 'approximation'], calculator: true,
    learn: ['Start with a guess x₀ and follow the tangent line to the x-axis.', 'xₙ₊₁ = xₙ − f(xₙ)/f′(xₙ).'],
    keyIdea: 'xₙ₊₁ = xₙ − f(xₙ) / f′(xₙ)',
    realWorld: 'How computers compute square roots.',
    explainPrompt: 'What is the geometric idea behind Newton’s method?', explainKeywords: ['tangent', 'x-intercept', 'approximation', 'repeat'],
  }),

  // ───────────────────────── LINEAR ALGEBRA
  S('matrix-mult', 'Matrix Multiplication', 'linear-algebra', 13, ['systems'], {
    summary: 'Row-by-column products.', tags: ['matrices', 'matrix multiplication', 'linear algebra'], visual: true,
    learn: ['Entry (i, j) of AB = row i of A · column j of B.', 'AB is defined when A’s columns = B’s rows; usually AB ≠ BA.'],
    keyIdea: '(AB)ᵢⱼ = Σₖ AᵢₖBₖⱼ',
    realWorld: 'Computer graphics transformations; neural networks.',
    explainPrompt: 'Why is matrix multiplication not commutative?', explainKeywords: ['order', 'rows', 'columns', 'transformations'],
  }),
  S('determinants', 'Determinants', 'linear-algebra', 13, ['matrix-mult'], {
    summary: 'Compute 2×2 and 3×3 determinants.', tags: ['determinant', 'matrices', 'invertible'], visual: true,
    learn: ['det [[a, b], [c, d]] = ad − bc.', 'det = 0 ⇔ the matrix is not invertible; |det| scales area/volume.'],
    keyIdea: 'det [[a,b],[c,d]] = ad − bc',
    realWorld: 'Area scaling in transformations; solving systems.',
    explainPrompt: 'What does a determinant of zero tell you?', explainKeywords: ['not invertible', 'singular', 'area', 'zero', 'dependent'],
  }),
  S('eigenvalues', 'Eigenvalues', 'linear-algebra', 14, ['determinants', 'quadratic-formula'], {
    summary: 'Solve det(A − λI) = 0.', tags: ['eigenvalues', 'eigenvectors', 'characteristic polynomial'], visual: true,
    learn: ['Av = λv: the matrix only stretches v by λ.', 'Eigenvalues are roots of det(A − λI) = 0.'],
    keyIdea: 'det(A − λI) = 0',
    realWorld: 'Google PageRank, vibration modes, PCA.',
    explainPrompt: 'What is special about an eigenvector?', explainKeywords: ['direction', 'stretch', 'scale', 'same'],
  }),

  // ───────────────────────── DISCRETE MATH, NUMBER THEORY, PROOFS, ALGEBRA, ANALYSIS
  S('gcd-euclid', 'GCD & the Euclidean Algorithm', 'discrete', 13, ['primes-factors'], {
    summary: 'gcd(a, b) = gcd(b, a mod b).', tags: ['number theory', 'gcd', 'euclidean algorithm'],
    learn: ['Repeatedly replace (a, b) with (b, a mod b).', 'The last non-zero remainder is the gcd.'],
    keyIdea: 'gcd(a, b) = gcd(b, a mod b)',
    realWorld: 'Simplifying ratios; cryptography (RSA).',
    explainPrompt: 'Why does the Euclidean algorithm always terminate?', explainKeywords: ['remainder', 'smaller', 'decrease', 'zero'],
  }),
  S('modular', 'Modular Arithmetic', 'discrete', 13, ['long-division'], {
    summary: 'Clock arithmetic and remainders.', tags: ['modular arithmetic', 'mod', 'congruence', 'number theory'],
    learn: ['a mod n is the remainder when a is divided by n.', 'You can reduce before adding or multiplying: (a·b) mod n = ((a mod n)(b mod n)) mod n.'],
    keyIdea: 'a ≡ b (mod n) ⇔ n | (a − b)',
    realWorld: 'Clock times, check digits, cryptography.',
    explainPrompt: 'Why can you reduce numbers mod n before multiplying?', explainKeywords: ['remainder', 'multiple', 'same', 'divisible'],
  }),
  S('logic-truth', 'Logic & Truth Tables', 'discrete', 13, [], {
    summary: 'AND, OR, NOT, implication.', tags: ['logic', 'truth tables', 'propositions', 'proofs'],
    learn: ['p → q is false only when p is true and q is false.', 'The contrapositive ¬q → ¬p is equivalent to p → q.'],
    keyIdea: 'p → q ≡ ¬q → ¬p',
    realWorld: 'Programming conditions and circuit design.',
    explainPrompt: 'Why is an implication true when its hypothesis is false?', explainKeywords: ['vacuous', 'promise', 'false', 'hypothesis'],
  }),
  S('proofs-induction', 'Proof by Induction', 'discrete', 14, ['arith-sequence', 'logic-truth'], {
    summary: 'Base case + inductive step.', tags: ['induction', 'proofs', 'sums'],
    learn: ['Prove P(1). Then assume P(k) and show P(k + 1).', 'Like dominoes: the first falls, and each knocks the next.'],
    keyIdea: '1 + 2 + … + n = n(n + 1)/2',
    realWorld: 'Proving algorithms are correct.',
    explainPrompt: 'Explain why induction proves a statement for all n.', explainKeywords: ['base case', 'inductive step', 'assume', 'dominoes', 'next'],
  }),
  S('group-order', 'Groups: Order of an Element', 'discrete', 15, ['modular'], {
    summary: 'Abstract algebra in ℤₙ.', tags: ['abstract algebra', 'groups', 'cyclic', 'order'],
    learn: ['In (ℤₙ, +), the order of a is the smallest k > 0 with k·a ≡ 0.', 'That order equals n / gcd(a, n).'],
    keyIdea: 'ord(a) = n / gcd(a, n) in ℤₙ',
    realWorld: 'Symmetries, cryptography, error-correcting codes.',
    explainPrompt: 'Why does the order of a divide n in ℤₙ?', explainKeywords: ['lagrange', 'subgroup', 'divides', 'cyclic'],
  }),
  S('real-analysis-sup', 'Supremum & Infimum', 'discrete', 15, ['inequalities', 'limits'], {
    summary: 'Least upper bounds of sets of reals.', tags: ['real analysis', 'supremum', 'infimum', 'bounds'],
    learn: ['sup S is the least upper bound — it need not belong to S.', 'Example: sup{1 − 1/n} = 1, but 1 is never reached.'],
    keyIdea: 'sup S = smallest M with s ≤ M for all s ∈ S',
    realWorld: 'Foundations of limits and optimization.',
    explainPrompt: 'Give an example of a set whose supremum is not in the set.', explainKeywords: ['upper bound', 'least', 'not contained', 'approach'],
  }),

  // ───────────────────────── MENTAL MATH
  S('mental-add', 'Mental Addition & Subtraction', 'mental', 2, ['add-2digit'], {
    summary: 'Fast strategies: make tens, compensate.', tags: ['mental math', 'quick', 'addition'],
    learn: ['Make a ten: 8 + 7 = 8 + 2 + 5 = 15.', 'Compensate: 49 + 26 = 50 + 26 − 1 = 75.'],
    keyIdea: 'Round, compute, then adjust.',
    realWorld: 'Adding up a bill in your head.',
    explainPrompt: 'Describe a mental strategy for 49 + 36.', explainKeywords: ['round', 'adjust', 'ten', 'compensate'],
  }),
  S('mental-mult', 'Mental Multiplication', 'mental', 5, ['multi-digit-mult'], {
    summary: 'Split, double, and use nearby facts.', tags: ['mental math', 'multiplication tricks'],
    learn: ['Split: 14 × 6 = 10 × 6 + 4 × 6 = 84.', 'Double and halve: 25 × 16 = 50 × 8 = 400.'],
    keyIdea: 'Break numbers into friendly parts.',
    realWorld: 'Estimating the cost of several items.',
    explainPrompt: 'How would you compute 25 × 24 in your head?', explainKeywords: ['split', 'double', 'halve', '100'],
  }),
  S('mental-percent', 'Mental Percentages', 'mental', 7, ['percent-of'], {
    summary: '10%, 5%, 1% building blocks.', tags: ['mental math', 'percent', 'tips'],
    learn: ['10% = move the decimal one place left.', 'Build others: 15% = 10% + 5%, 5% = half of 10%.'],
    keyIdea: '15% of 60 = 6 + 3 = 9',
    realWorld: 'Tips and discounts on the spot.',
    explainPrompt: 'How do you find 15% of a number mentally?', explainKeywords: ['10%', 'half', '5%', 'add'],
  }),
  S('mental-squares', 'Mental Squares & Estimation', 'mental', 8, ['exponents'], {
    summary: 'Square numbers fast with patterns.', tags: ['mental math', 'squares', 'estimation'],
    learn: ['(a + b)² = a² + 2ab + b²: 31² = 900 + 60 + 1 = 961.', 'Numbers ending in 5: 35² = 3×4 then 25 → 1225.'],
    keyIdea: '(a ± b)² = a² ± 2ab + b²',
    realWorld: 'Quick area estimates.',
    explainPrompt: 'Explain the trick for squaring numbers ending in 5.', explainKeywords: ['next', 'multiply', '25', 'tens'],
  }),

  // ───────────────────────── REAL-WORLD MATH
  S('money', 'Counting Money', 'realworld', 2, ['add-2digit'], {
    summary: 'Add coins and make change.', tags: ['money', 'coins', 'change'], visual: true,
    learn: ['Count the biggest coins first, then add smaller ones.', 'Change = amount paid − price.'],
    keyIdea: 'Change = paid − cost',
    realWorld: 'Buying a snack with coins.',
    explainPrompt: 'How do you figure out your change?', explainKeywords: ['subtract', 'paid', 'cost', 'price'],
  }),
  S('recipe-scaling', 'Scaling Recipes', 'realworld', 5, ['frac-mult'], {
    summary: 'Multiply ingredient amounts by a scale factor.', tags: ['cooking', 'recipes', 'scale', 'fractions'],
    learn: ['Scale factor = servings wanted ÷ servings in recipe.', 'Multiply every ingredient by the scale factor.'],
    keyIdea: 'new amount = old amount × (new servings ÷ old servings)',
    realWorld: 'Cooking for more or fewer people.',
    explainPrompt: 'How do you change a recipe for 4 into a recipe for 6?', explainKeywords: ['scale factor', 'multiply', 'divide', 'each'],
  }),
  S('shopping-discounts', 'Discounts & Sales Tax', 'realworld', 7, ['percent-of'], {
    summary: 'Sale prices, tax and total cost.', tags: ['shopping', 'discount', 'tax', 'sale'],
    learn: ['Sale price = price × (1 − discount).', 'With tax: total = price × (1 + tax rate).'],
    keyIdea: '$80 at 25% off → 80 × 0.75 = $60',
    realWorld: 'Is the sale really a good deal?',
    explainPrompt: 'Why is "30% off then 10% off" not the same as 40% off?', explainKeywords: ['new price', 'multiply', 'smaller', 'base'],
  }),
  S('speed-distance', 'Speed, Distance & Time', 'realworld', 7, ['unit-rate'], {
    summary: 'd = s × t for travel problems.', tags: ['travel', 'speed', 'distance', 'time', 'rate'],
    learn: ['distance = speed × time.', 'Rearrange: time = distance ÷ speed; speed = distance ÷ time.'],
    keyIdea: 'd = s · t',
    realWorld: 'How long a road trip will take.',
    explainPrompt: 'How do you find travel time from distance and speed?', explainKeywords: ['divide', 'distance', 'speed', 'units'],
  }),
  S('fuel-cost', 'Fuel & Trip Costs', 'realworld', 7, ['unit-rate'], {
    summary: 'Fuel used and trip cost from efficiency.', tags: ['travel', 'fuel', 'gas', 'cost'],
    learn: ['Fuel needed = distance ÷ efficiency (km per litre or miles per gallon).', 'Cost = fuel needed × price per unit.'],
    keyIdea: 'cost = (distance ÷ efficiency) × price',
    realWorld: 'Budgeting a road trip.',
    explainPrompt: 'Explain how to estimate the fuel cost of a trip.', explainKeywords: ['distance', 'efficiency', 'price', 'multiply'],
  }),
  S('currency', 'Currency Conversion', 'realworld', 7, ['proportions'], {
    summary: 'Convert money with exchange rates.', tags: ['travel', 'currency', 'exchange rate'],
    learn: ['If 1 USD = r EUR, then x USD = x·r EUR.', 'To go back, divide by r.'],
    keyIdea: 'amount × rate',
    realWorld: 'Shopping abroad.',
    explainPrompt: 'How do you convert back from euros to dollars?', explainKeywords: ['divide', 'rate', 'inverse', 'multiply'],
  }),
  S('sports-stats', 'Sports Statistics', 'realworld', 7, ['percent-of'], {
    summary: 'Percentages, averages and rates in sports.', tags: ['sports', 'statistics', 'percent', 'average'],
    learn: ['Shooting % = made ÷ attempted × 100.', 'Points per game = total points ÷ games.'],
    keyIdea: 'rate = successes ÷ attempts',
    realWorld: 'Comparing players fairly.',
    explainPrompt: 'Why compare percentages rather than totals between players?', explainKeywords: ['attempts', 'fair', 'different', 'rate'],
  }),
  S('profit-margin', 'Revenue, Profit & Margins', 'realworld', 8, ['percent-of'], {
    summary: 'Business math basics.', tags: ['business', 'profit', 'revenue', 'margin', 'expenses'],
    learn: ['Revenue = price × quantity. Profit = revenue − expenses.', 'Profit margin = profit ÷ revenue × 100%.'],
    keyIdea: 'margin = (revenue − cost) / revenue',
    realWorld: 'Running a lemonade stand or a company.',
    explainPrompt: 'What is the difference between revenue and profit?', explainKeywords: ['expenses', 'subtract', 'income', 'costs'],
  }),
  S('simple-interest', 'Simple Interest', 'realworld', 8, ['percent-of'], {
    summary: 'I = P r t.', tags: ['finance', 'interest', 'loans', 'savings'],
    learn: ['Simple interest is paid only on the original principal.', 'I = P × r × t, total = P + I.'],
    keyIdea: 'I = Prt',
    realWorld: 'Interest on a short-term loan.',
    explainPrompt: 'How is simple interest calculated?', explainKeywords: ['principal', 'rate', 'time', 'multiply'],
  }),
  S('engineering-formulas', 'Engineering Formulas', 'realworld', 9, ['variables-eval'], {
    summary: 'Force, work, pressure and unit sense.', tags: ['engineering', 'physics', 'force', 'work', 'pressure', 'measurement'],
    learn: ['F = m·a (newtons). Work W = F·d (joules). Pressure P = F/A (pascals).', 'Always carry units through a calculation.'],
    keyIdea: 'F = ma, W = Fd, P = F/A',
    realWorld: 'Designing a bridge or lifting a load.',
    explainPrompt: 'Why should you track units in engineering calculations?', explainKeywords: ['units', 'check', 'consistent', 'errors'],
  }),
  S('compound-interest', 'Compound Interest', 'realworld', 10, ['exponent-rules', 'percent-of'], {
    summary: 'A = P(1 + r/n)ⁿᵗ.', tags: ['finance', 'compound interest', 'investments', 'savings'], calculator: true,
    learn: ['Interest earns interest: each period multiplies by (1 + r/n).', 'A = P(1 + r/n)^(n·t).'],
    keyIdea: 'A = P(1 + r/n)^(nt)',
    realWorld: 'Retirement savings and credit card debt.',
    explainPrompt: 'Why does compound interest grow faster than simple interest?', explainKeywords: ['interest on interest', 'multiply', 'grows', 'exponential'],
  }),
  S('growth-rates', 'Growth Rates & CAGR', 'realworld', 10, ['percent-change', 'exponent-rules'], {
    summary: 'Average annual growth.', tags: ['finance', 'cagr', 'growth', 'corporate finance'], calculator: true,
    learn: ['CAGR = (end/start)^(1/years) − 1.', 'It is the steady rate giving the same overall growth.'],
    keyIdea: 'CAGR = (V_end / V_start)^(1/t) − 1',
    realWorld: 'Comparing company revenue growth.',
    explainPrompt: 'Why not just average the yearly growth percentages?', explainKeywords: ['compound', 'multiply', 'geometric', 'average'],
  }),
  S('present-value', 'Present & Future Value', 'realworld', 12, ['compound-interest'], {
    summary: 'Discounting future money.', tags: ['finance', 'present value', 'discounting', 'npv', 'time value of money'], calculator: true,
    learn: ['FV = PV(1 + r)ᵗ, so PV = FV / (1 + r)ᵗ.', 'Money today is worth more than the same money later.'],
    keyIdea: 'PV = FV / (1 + r)ᵗ',
    realWorld: 'Valuing investments and companies.',
    explainPrompt: 'Why is $100 next year worth less than $100 today?', explainKeywords: ['interest', 'invest', 'grow', 'discount'],
  }),
  S('mortgage', 'Loans & Mortgages', 'realworld', 12, ['compound-interest', 'geom-series'], {
    summary: 'Monthly payments with the amortization formula.', tags: ['finance', 'mortgage', 'loan', 'amortization'], calculator: true,
    learn: ['Monthly rate i = annual rate ÷ 12; n = number of payments.', 'Payment M = P·i(1 + i)ⁿ / ((1 + i)ⁿ − 1).'],
    keyIdea: 'M = P·i(1+i)ⁿ / ((1+i)ⁿ − 1)',
    realWorld: 'Buying a home or car.',
    explainPrompt: 'Why do you pay much more than the loan amount over a mortgage?', explainKeywords: ['interest', 'years', 'compound', 'payments'],
  }),

  // ───────────────────────── PUZZLES & LOGIC
  S('k-patterns', 'Patterns', 'puzzles', 0, [], {
    summary: 'Find what comes next.', tags: ['patterns', 'sequence'], visual: true,
    learn: ['Look for the part that repeats.', 'Say the pattern out loud: red, blue, red, blue…'],
    keyIdea: 'Find the repeating unit.',
    realWorld: 'Patterns on clothes and tiles.',
    explainPrompt: 'How did you figure out what comes next?', explainKeywords: ['repeat', 'pattern', 'same', 'again'],
  }),
  S('sequences-next', 'Number Patterns', 'puzzles', 4, ['mult-facts'], {
    summary: 'Find rules in number sequences.', tags: ['sequences', 'patterns', 'puzzles'],
    learn: ['Check differences between terms.', 'If differences aren’t constant, try ratios or the differences of differences.'],
    keyIdea: 'Look at the change from one term to the next.',
    realWorld: 'Spotting trends in data.',
    explainPrompt: 'Describe how you found the rule.', explainKeywords: ['difference', 'add', 'multiply', 'rule'],
  }),
  S('missing-digit', 'Missing Number Puzzles', 'puzzles', 5, ['multi-digit-mult'], {
    summary: 'Reason backwards to fill in blanks.', tags: ['puzzles', 'reasoning', 'inverse'],
    learn: ['Use inverse operations to work backwards.', 'Check your answer in the original sentence.'],
    keyIdea: '□ × 7 = 56 → □ = 56 ÷ 7',
    realWorld: 'Detective-style reasoning.',
    explainPrompt: 'How did working backwards help?', explainKeywords: ['inverse', 'backwards', 'undo', 'check'],
  }),
  S('logic-puzzles', 'Logic Word Puzzles', 'puzzles', 6, ['two-step-eq'], {
    summary: 'Age, coin and number riddles.', tags: ['puzzles', 'logic', 'word problems', 'olympiad'],
    learn: ['Name the unknown, write what you know as equations.', 'Solve and check against every clue.'],
    keyIdea: 'Translate words → equations.',
    realWorld: 'Competition and Olympiad problems.',
    explainPrompt: 'How did you turn the clues into math?', explainKeywords: ['unknown', 'equation', 'clue', 'check'],
  }),
];

export const SKILL_MAP: Record<string, SkillMeta> = Object.fromEntries(SKILLS.map((s) => [s.id, s]));
export const getSkill = (id: string): SkillMeta | undefined => SKILL_MAP[id];
